# Math Operations

# Operations in column

In [6]:
import pandas as pd
import numpy as np

In [7]:
df_exam=pd.read_csv('StudentsPerformance.csv')
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [8]:
#select a column and calculate total sum
df_exam['math score'].sum()

66089

In [9]:
#count,mean,std,max and min
df_exam['math score'].count()
df_exam['math score'].min()

0

In [10]:
#easier calculations with .describe()
df_exam.describe ()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Operation in rows

In [12]:
#calculating the sum in a row
df_exam['math score']+ df_exam['reading score']+ df_exam['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [13]:
#calculting the average score and assingning the result to a new column 
#df_exam['average']=(df_exam['math score']+ df_exam['reading score']+ df_exam['writing score'])/3

In [14]:
df_exam.round(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# The value_counts() Method

# 1 Value counts

In [17]:
#counting gender elements 
#len fucntion 
len(df_exam['gender'])
# .count()method
df_exam['gender'].count()

1000

In [18]:
#counting gender elements by category
df_exam['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [19]:
#return the relative frequency(divide all the values by the sum of values)
df_exam['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [20]:
#counting "parental level of education" elements by catogery
df_exam['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [21]:
df_exam['parental level of education'].value_counts(normalize=True)

parental level of education
some college          0.226
associate's degree    0.222
high school           0.196
some high school      0.179
bachelor's degree     0.118
master's degree       0.059
Name: proportion, dtype: float64

# Sort a DataFrame

In [23]:
#sort by one column
df_exam.sort_values('math score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

In [24]:
#sort descending by one column
df_exam.sort_values('math score', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
458,female,group E,bachelor's degree,standard,none,100,100,100
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [25]:
#sort descednding by multiple column
df_exam.sort_values(['math score','reading score'],ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [26]:
#sort descednding by multiple column and update dataframe
df_exam.sort_values(['math score','reading score'],ascending=False, inplace=True)
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [27]:
#sort descending with a key function
df_exam.sort_values('race/ethnicity',ascending=True, key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
741,female,group A,associate's degree,free/reduced,none,37,57,56
151,male,group A,bachelor's degree,standard,none,77,67,68
811,male,group A,high school,free/reduced,none,45,47,49
112,male,group A,associate's degree,standard,none,54,53,47
25,male,group A,master's degree,free/reduced,none,73,74,72
...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65
915,female,group E,some college,standard,none,68,70,66
592,male,group E,bachelor's degree,standard,none,68,68,64
479,male,group E,associate's degree,standard,none,76,71,67
517,female,group E,some college,standard,completed,66,74,73

# Create Index

In [29]:
import random

In [30]:
#creating non repetitive values for the index
new_index=np.arange(0,1000)

In [31]:
#shuffling the indexes
random.shuffle(new_index)

In [32]:
#create a new column with new index 
df_exam['new_index']=new_index

# Set Index

In [34]:
# set new index column as index
df_exam.set_index('new_index',inplace=True)

In [35]:
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
400,male,group E,associate's degree,free/reduced,completed,100,100,93
947,female,group E,bachelor's degree,standard,none,100,100,100
668,male,group E,bachelor's degree,standard,completed,100,100,100
148,female,group E,associate's degree,standard,none,100,100,100
879,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
598,female,group C,some college,free/reduced,none,22,39,33
259,female,group B,some college,standard,none,19,38,32
210,female,group B,some high school,free/reduced,none,18,32,28
866,female,group B,high school,free/reduced,none,8,24,23
92,female,group C,some high school,free/reduced,none,0,17,10

In [36]:
# sort dataframe by new index
df_exam.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,male,group B,associate's degree,free/reduced,completed,82,78,74
1,male,group C,high school,standard,none,70,56,51
2,female,group B,some high school,standard,none,67,89,82
3,male,group B,associate's degree,standard,none,65,54,57
4,male,group A,bachelor's degree,standard,completed,75,58,62
...,...,...,...,...,...,...,...,...
995,male,group D,some high school,free/reduced,none,45,37,37
996,female,group B,associate's degree,standard,completed,59,70,66
997,male,group A,some high school,standard,none,71,62,50
998,female,group D,high school,standard,none,69,77,73
999,female,group C,associate's degree,standard,completed,68,86,84

In [37]:
df_exam.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group C,associate's degree,standard,completed,68,86,84
998,female,group D,high school,standard,none,69,77,73
997,male,group A,some high school,standard,none,71,62,50
996,female,group B,associate's degree,standard,completed,59,70,66
995,male,group D,some high school,free/reduced,none,45,37,37
...,...,...,...,...,...,...,...,...
4,male,group A,bachelor's degree,standard,completed,75,58,62
3,male,group B,associate's degree,standard,none,65,54,57
2,female,group B,some high school,standard,none,67,89,82
1,male,group C,high school,standard,none,70,56,51
0,male,group B,associate's degree,free/reduced,completed,82,78,74

# Rename columns and index with rename()

In [39]:
# rename column and overwrite values of the dataframe 
df_exam=df_exam.rename(columns={'gender':'Gender'})
df_exam.head()

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
400,male,group E,associate's degree,free/reduced,completed,100,100,93
947,female,group E,bachelor's degree,standard,none,100,100,100
668,male,group E,bachelor's degree,standard,completed,100,100,100
148,female,group E,associate's degree,standard,none,100,100,100
879,male,group D,some college,standard,completed,100,97,99

In [40]:
#rename multiple column and update the dataframe with inplace argument 
df_exam.rename(
    columns={
        'math score': 'math_score',
        'reading score': 'reading_score'
    },
    inplace=True
)

In [41]:
df_exam.head(2)

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math_score,reading_score,writing score
new_index,,,,,,,,
400,male,group E,associate's degree,free/reduced,completed,100,100,93
947,female,group E,bachelor's degree,standard,none,100,100,100

# Rename Index

In [75]:
#rename index 0,1 and 2 and update the dataframe
df_exam.rename(index={0:'A',1:'B',2:'C'},inplace=True)

In [ ]:
df_exam.head(3)