In [37]:
import pandas as pd
import numpy as np

# Creating Data Frame from an array

In [39]:
#creating an array
data=np.array([[1,4],[2,5],[3,6]])

In [40]:
#creating a dataframe 
df=pd.DataFrame(data,index=['row1','row2','row3'],
            columns=['col1','col2'])
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Cretaing a DataFrame form a Dictionary

In [42]:
states=['california','Texas','florida','New York']
population =[39613493,2970311,21944577,1929981]

In [43]:
#storing lists within a dictionary
dict_state ={'states':states,'population':population}
dict_state

{'states': ['california', 'Texas', 'florida', 'New York'],
 'population': [39613493, 2970311, 21944577, 1929981]}

In [44]:
#cretaing the dataframe
df_pop=pd.DataFrame(dict_state)
df_pop

       states  population
0  california    39613493
1       Texas     2970311
2     florida    21944577
3    New York     1929981

# Creating a DataFrame from CSV file

In [46]:
df_exam=pd.read_csv('StudentsPerformance.csv')

In [47]:
df_exam.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

In [48]:
 df_exam.tail(1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
999,female,group D,some college,free/reduced,none,77,86,86

In [49]:
#accessing shape attribute
df_exam.shape

(1000, 8)

In [66]:
#display n rows
pd.set_option('display.max_rows',1000)
#df_exam

In [51]:
#getting access to the index attribute 
df_exam.index

RangeIndex(start=0, stop=1000, step=1)

In [52]:
#getting acess to the column attribute 
df_exam.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [53]:
#data types of each column
df_exam.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [54]:
#displaying the info of the dataframe 
df_exam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [55]:
#describing the basic statistics of the dataframe
df_exam.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# functions

In [57]:
#length of the dataframe(number of rows)
len(df_exam)

1000

In [58]:
#highest index of the dataframe
max(df_exam.index)

999

In [59]:
#rounding 
#round(df_exam,2)

# Selecting one column

In [61]:
#select a column with[]
#df_exam['gender']

In [62]:
#check out the data type of a column
type(df_exam['gender'])

pandas.core.series.Series

In [63]:
#series:attributes and methods
df_exam['gender'].index
df_exam['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [87]:
df_exam['math score']

0       72
1       69
2       90
3       47
4       76
5       71
6       88
7       40
8       64
9       38
10      58
11      40
12      65
13      78
14      50
15      69
16      88
17      18
18      46
19      54
20      66
21      65
22      44
23      69
24      74
25      73
26      69
27      67
28      70
29      62
30      69
31      63
32      56
33      40
34      97
35      81
36      74
37      50
38      75
39      57
40      55
41      58
42      53
43      59
44      50
45      65
46      55
47      66
48      57
49      82
50      53
51      77
52      53
53      88
54      71
55      33
56      82
57      52
58      58
59       0
60      79
61      39
62      62
63      69
64      59
65      67
66      45
67      60
68      61
69      39
70      58
71      63
72      41
73      61
74      49
75      44
76      30
77      80
78      61
79      62
80      47
81      49
82      50
83      72
84      42
85      73
86      76
87      71
88      58
89      73
90      65
91      27
92      71
93      43
94      79
95      78
96      65
97      63
98      58
99      65
100     79
101     68
102     85
103     60
104     98
105     58
106     87
107     66
108     52
109     70
110     77
111     62
112     54
113     51
114     99
115     84
116     75
117     78
118     51
119     55
120     79
121     91
122     88
123     63
124     83
125     87
126     72
127     65
128     82
129     51
130     89
131     53
132     87
133     75
134     74
135     58
136     51
137     70
138     59
139     71
140     76
141     59
142     42
143     57
144     88
145     22
146     88
147     73
148     68
149    100
150     62
151     77
152     59
153     54
154     62
155     70
156     66
157     60
158     61
159     66
160     82
161     75
162     49
163     52
164     81
165     96
166     53
167     58
168     68
169     67
170     72
171     94
172     79
173     63
174     43
175     81
176     46
177     71
178     52
179     97
180     62
181     46
182     50
183     65
184     45
185     65
186     80
187     62
188     48
189     77
190     66
191     76
192     62
193     77
194     69
195     61
196     59
197     55
198     45
199     78
200     67
201     65
202     69
203     57
204     59
205     74
206     82
207     81
208     74
209     58
210     80
211     35
212     42
213     60
214     87
215     84
216     83
217     34
218     66
219     61
220     56
221     87
222     55
223     86
224     52
225     45
226     72
227     57
228     68
229     88
230     76
231     46
232     67
233     92
234     83
235     80
236     63
237     64
238     54
239     84
240     73
241     80
242     56
243     59
244     75
245     85
246     89
247     58
248     65
249     68
250     47
251     71
252     60
253     80
254     54
255     62
256     64
257     78
258     70
259     65
260     64
261     79
262     44
263     99
264     76
265     59
266     63
267     69
268     88
269     71
270     69
271     58
272     47
273     65
274     88
275     83
276     85
277     59
278     65
279     73
280     53
281     45
282     73
283     70
284     37
285     81
286     97
287     67
288     88
289     77
290     76
291     86
292     63
293     65
294     78
295     67
296     46
297     71
298     40
299     90
300     81
301     56
302     67
303     80
304     74
305     69
306     99
307     51
308     53
309     49
310     73
311     66
312     67
313     68
314     59
315     71
316     77
317     83
318     63
319     56
320     67
321     75
322     71
323     43
324     41
325     82
326     61
327     28
328     82
329     41
330     71
331     47
332     62
333     90
334     83
335     61
336     76
337     49
338     24
339     35
340     58
341     61
342     69
343     67
344     79
345     72
346     62
347     77
348     75
349     87
350     52
351     66
352     63
353     46
354     59
355     61
356     63
357     42
358     59
359     80
360     58
361     85
362     52
363     27
364     59
365     49
366     69
367     61
368     44
369     73
370     84
371     45
372     74
373     82
374     59
375     46
376     80
377     85
378     71
379     66
380     80
381     87
382     79
383     38
384     38
385     67
386     64
387     57
388     62
389     73
390     73
391     77
392     76
393     57
394     65
395     48
396     50
397     85
398     74
399     60
400     59
401     53
402     49
403     88
404     54
405     63
406     65
407     82
408     52
409     87
410     70
411     84
412     71
413     63
414     51
415     84
416     71
417     74
418     68
419     57
420     82
421     57
422     47
423     59
424     41
425     62
426     86
427     69
428     65
429     68
430     64
431     61
432     61
433     47
434     73
435     50
436     75
437     75
438     70
439     89
440     67
441     78
442     59
443     73
444     79
445     67
446     69
447     86
448     47
449     81
450     64
451    100
452     65
453     65
454     53
455     37
456     79
457     53
458    100
459     72
460     53
461     54
462     71
463     77
464     75
465     84
466     26
467     72
468     77
469     91
470     83
471     63
472     68
473     59
474     90
475     71
476     76
477     80
478     55
479     76
480     73
481     52
482     68
483     59
484     49
485     70
486     61
487     60
488     64
489     79
490     65
491     64
492     83
493     81
494     54
495     68
496     54
497     59
498     66
499     76
500     74
501     94
502     63
503     95
504     40
505     82
506     68
507     55
508     79
509     86
510     76
511     64
512     62
513     54
514     77
515     76
516     74
517     66
518     66
519     67
520     71
521     91
522     69
523     54
524     53
525     68
526     56
527     36
528     29
529     62
530     68
531     47
532     62
533     79
534     73
535     66
536     51
537     51
538     85
539     97
540     75
541     79
542     81
543     82
544     64
545     78
546     92
547     72
548     62
549     79
550     79
551     87
552     40
553     77
554     53
555     32
556     55
557     61
558     53
559     73
560     74
561     63
562     96
563     63
564     48
565     48
566     92
567     61
568     63
569     68
570     71
571     91
572     53
573     50
574     74
575     40
576     61
577     81
578     48
579     53
580     81
581     77
582     63
583     73
584     69
585     65
586     55
587     44
588     54
589     48
590     58
591     71
592     68
593     74
594     92
595     56
596     30
597     53
598     69
599     65
600     54
601     29
602     76
603     60
604     84
605     75
606     85
607     40
608     61
609     58
610     69
611     58
612     94
613     65
614     82
615     60
616     37
617     88
618     95
619     65
620     35
621     62
622     58
623    100
624     61
625    100
626     69
627     61
628     49
629     44
630     67
631     79
632     66
633     75
634     84
635     71
636     67
637     80
638     86
639     76
640     41
641     74
642     72
643     74
644     70
645     65
646     59
647     64
648     50
649     69
650     51
651     68
652     85
653     65
654     73
655     62
656     77
657     69
658     43
659     90
660     74
661     73
662     55
663     65
664     80
665     50
666     63
667     77
668     73
669     81
670     66
671     52
672     69
673     65
674     69
675     50
676     73
677     70
678     81
679     63
680     67
681     60
682     62
683     29
684     62
685     94
686     85
687     77
688     53
689     93
690     49
691     73
692     66
693     77
694     49
695     79
696     75
697     59
698     57
699     66
700     79
701     57
702     87
703     63
704     59
705     62
706     46
707     66
708     89
709     42
710     93
711     80
712     98
713     81
714     60
715     76
716     73
717     96
718     76
719     91
720     62
721     55
722     74
723     50
724     47
725     81
726     65
727     68
728     73
729     53
730     68
731     55
732     87
733     55
734     53
735     67
736     92
737     53
738     81
739     61
740     80
741     37
742     81
743     59
744     55
745     72
746     69
747     69
748     50
749     87
750     71
751     68
752     79
753     77
754     58
755     84
756     55
757     70
758     52
759     69
760     53
761     48
762     78
763     62
764     60
765     74
766     58
767     76
768     68
769     58
770     52
771     75
772     52
773     62
774     66
775     49
776     66
777     35
778     72
779     94
780     46
781     77
782     76
783     52
784     91
785     32
786     72
787     19
788     68
789     52
790     48
791     60
792     66
793     89
794     42
795     57
796     70
797     70
798     69
799     52
800     67
801     76
802     87
803     82
804     73
805     75
806     64
807     41
808     90
809     59
810     51
811     45
812     54
813     87
814     72
815     94
816     45
817     61
818     60
819     77
820     85
821     78
822     49
823     71
824     48
825     62
826     56
827     65
828     69
829     68
830     61
831     74
832     64
833     77
834     58
835     60
836     73
837     75
838     58
839     66
840     39
841     64
842     23
843     74
844     40
845     90
846     91
847     64
848     59
849     80
850     71
851     61
852     87
853     82
854     62
855     97
856     75
857     65
858     52
859     87
860     53
861     81
862     39
863     71
864     97
865     82
866     59
867     61
868     78
869     49
870     59
871     70
872     82
873     90
874     43
875     80
876     81
877     57
878     59
879     64
880     63
881     71
882     64
883     55
884     51
885     62
886     93
887     54
888     69
889     44
890     86
891     85
892     50
893     88
894     59
895     32
896     36
897     63
898     67
899     65
900     85
901     73
902     34
903     93
904     67
905     88
906     57
907     79
908     67
909     70
910     50
911     69
912     52
913     47
914     46
915     68
916    100
917     44
918     57
919     91
920     69
921     35
922     72
923     54
924     74
925     74
926     64
927     65
928     46
929     48
930     67
931     62
932     61
933     70
934     98
935     70
936     67
937     57
938     85
939     77
940     72
941     78
942     81
943     61
944     58
945     54
946     82
947     49
948     49
949     57
950     94
951     75
952     74
953     58
954     62
955     72
956     84
957     92
958     45
959     75
960     56
961     48
962    100
963     65
964     72
965     62
966     66
967     63
968     68
969     75
970     89
971     78
972     53
973     49
974     54
975     64
976     60
977     62
978     55
979     91
980      8
981     81
982     79
983     78
984     74
985     57
986     40
987     81
988     44
989     67
990     86
991     65
992     55
993     62
994     63
995     88
996     62
997     59
998     68
999     77
Name: math score, dtype: int64

# selecting two or more columns

In [135]:
#select two columns using[[]]
#df_exam[['math score','gender']]

In [101]:
type(df_exam[['gender','math score']])

pandas.core.frame.DataFrame

# Adding a new column

In [106]:
#adding a new column with a scaler value 
df_exam['langauage'] = 70
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,langauage
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
5,female,group B,associate's degree,standard,none,71,83,78,70
6,female,group B,some college,standard,completed,88,95,92,70
7,male,group B,some college,free/reduced,none,40,43,39,70
8,male,group D,high school,free/reduced,completed,64,64,67,70
9,female,group B,high school,free/reduced,none,38,60,50,70
10,male,group C,associate's degree,standard,none,58,54,52,70
11,male,group D,associate's degree,standard,none,40,52,43,70
12,female,group B,high school,standard,none,65,81,73,70
13,male,group A,some college,standard,completed,78,72,70,70
14,female,group A,master's degree,standard,none,50,53,58,70
15,female,group C,some high school,standard,none,69,75,78,70
16,male,group C,high school,standard,none,88,89,86,70
17,female,group B,some high school,free/reduced,none,18,32,28,70
18,male,group C,master's degree,free/reduced,completed,46,42,46,70
19,female,group C,associate's degree,free/reduced,none,54,58,61,70
20,male,group D,high school,standard,none,66,69,63,70
21,female,group B,some college,free/reduced,completed,65,75,70,70
22,male,group D,some college,standard,none,44,54,53,70
23,female,group C,some high school,standard,none,69,73,73,70
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,70
25,male,group A,master's degree,free/reduced,none,73,74,72,70
26,male,group B,some college,standard,none,69,54,55,70
27,female,group C,bachelor's degree,standard,none,67,69,75,70
28,male,group C,high school,standard,none,70,70,65,70
29,female,group D,master's degree,standard,none,62,70,75,70
30,female,group D,some college,standard,none,69,74,74,70
31,female,group B,some college,standard,none,63,65,61,70
32,female,group E,master's degree,free/reduced,none,56,72,65,70
33,male,group D,some college,standard,none,40,42,38,70
34,male,group E,some college,standard,none,97,87,82,70
35,male,group E,associate's degree,standard,completed,81,81,79,70
36,female,group D,associate's degree,standard,none,74,81,83,70
37,female,group D,some high school,free/reduced,none,50,64,59,70
38,female,group D,associate's degree,free/reduced,completed,75,90,88,70
39,male,group B,associate's degree,free/reduced,none,57,56,57,70
40,male,group C,associate's degree,free/reduced,none,55,61,54,70
41,female,group C,associate's degree,standard,none,58,73,68,70
42,female,group B,associate's degree,standard,none,53,58,65,70
43,male,group B,some college,free/reduced,completed,59,65,66,70
44,female,group E,associate's degree,free/reduced,none,50,56,54,70
45,male,group B,associate's degree,standard,none,65,54,57,70
46,female,group A,associate's degree,standard,completed,55,65,62,70
47,female,group C,high school,standard,none,66,71,76,70
48,female,group D,associate's degree,free/reduced,completed,57,74,76,70
49,male,group C,high school,standard,completed,82,84,82,70
50,male,group E,some college,standard,none,53,55,48,70
51,male,group E,associate's degree,free/reduced,completed,77,69,68,70
52,male,group C,some college,standard,none,53,44,42,70
53,male,group D,high school,standard,none,88,78,75,70
54,female,group C,some high school,free/reduced,completed,71,84,87,70
55,female,group C,high school,free/reduced,none,33,41,43,70
56,female,group E,associate's degree,standard,completed,82,85,86,70
57,male,group D,associate's degree,standard,none,52,55,49,70
58,male,group D,some college,standard,completed,58,59,58,70
59,female,group C,some high school,free/reduced,none,0,17,10,70
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,70
61,male,group A,some high school,free/reduced,none,39,39,34,70
62,male,group A,associate's degree,free/reduced,none,62,61,55,70
63,female,group C,associate's degree,standard,none,69,80,71,70
64,female,group D,some high school,standard,none,59,58,59,70
65,male,group B,some high school,standard,none,67,64,61,70
66,male,group D,some high school,free/reduced,none,45,37,37,70
67,female,group C,some college,standard,none,60,72,74,70
68,male,group B,associate's degree,free/reduced,none,61,58,56,70
69,female,group C,associate's degree,standard,none,39,64,57,70
70,female,group D,some college,free/reduced,completed,58,63,73,70
71,male,group D,some college,standard,completed,63,55,63,70
72,female,group A,associate's degree,free/reduced,none,41,51,48,70
73,male,group C,some high school,free/reduced,none,61,57,56,70
74,male,group C,some high school,standard,none,49,49,41,70
75,male,group B,associate's degree,free/reduced,none,44,41,38,70
76,male,group E,some high school,standard,none,30,26,22,70
77,male,group A,bachelor's degree,standard,completed,80,78,81,70
78,female,group D,some high school,standard,completed,61,74,72,70
79,female,group E,master's degree,standard,none,62,68,68,70
80,female,group B,associate's degree,standard,none,47,49,50,70
81,male,group B,high school,free/reduced,none,49,45,45,70
82,male,group A,some college,free/reduced,completed,50,47,54,70
83,male,group E,associate's degree,standard,none,72,64,63,70
84,male,group D,high school,free/reduced,none,42,39,34,70
85,female,group C,some college,standard,none,73,80,82,70
86,female,group C,some college,free/reduced,none,76,83,88,70
87,female,group D,associate's degree,standard,none,71,71,74,70
88,female,group A,some college,standard,none,58,70,67,70
89,female,group D,some high school,standard,none,73,86,82,70
90,female,group C,bachelor's degree,standard,none,65,72,74,70
91,male,group C,high school,free/reduced,none,27,34,36,70
92,male,group C,high school,standard,none,71,79,71,70
93,male,group C,associate's degree,free/reduced,completed,43,45,50,70
94,female,group B,some college,standard,none,79,86,92,70
95,male,group C,associate's degree,free/reduced,completed,78,81,82,70
96,male,group B,some high school,standard,completed,65,66,62,70
97,female,group E,some college,standard,completed,63,72,70,70
98,female,group D,some college,free/reduced,none,58,67,62,70
99,female,group D,bachelor's degree,standard,none,65,67,62,70
100,male,group B,some college,standard,none,79,67,67,70
101,male,group D,bachelor's degree,standard,completed,68,74,74,70
102,female,group D,associate's degree,standard,none,85,91,89,70
103,male,group B,high school,standard,completed,60,44,47,70
104,male,group C,some college,standard,completed,98,86,90,70
105,female,group C,some college,standard,none,58,67,72,70
106,female,group D,master's degree,standard,none,87,100,100,70
107,male,group E,associate's degree,standard,completed,66,63,64,70
108,female,group B,associate's degree,free/reduced,none,52,76,70,70
109,female,group B,some high school,standard,none,70,64,72,70
110,female,group D,associate's degree,free/reduced,completed,77,89,98,70
111,male,group C,high school,standard,none,62,55,49,70
112,male,group A,associate's degree,standard,none,54,53,47,70
113,female,group D,some college,standard,none,51,58,54,70
114,female,group E,bachelor's degree,standard,completed,99,100,100,70
115,male,group C,high school,standard,none,84,77,74,70
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,70
117,female,group D,bachelor's degree,standard,none,78,82,79,70
118,female,group D,some high school,standard,none,51,63,61,70
119,female,group C,some college,standard,none,55,69,65,70
120,female,group C,bachelor's degree,standard,completed,79,92,89,70
121,male,group B,associate's degree,standard,completed,91,89,92,70
122,female,group C,some college,standard,completed,88,93,93,70
123,male,group D,high school,free/reduced,none,63,57,56,70
124,male,group E,some college,standard,none,83,80,73,70
125,female,group B,high school,standard,none,87,95,86,70
126,male,group B,some high school,standard,none,72,68,67,70
127,male,group D,some college,standard,completed,65,77,74,70
128,male,group D,master's degree,standard,none,82,82,74,70
129,female,group A,bachelor's degree,standard,none,51,49,51,70
130,male,group D,master's degree,standard,none,89,84,82,70
131,male,group C,some high school,free/reduced,completed,53,37,40,70
132,male,group E,some college,free/reduced,completed,87,74,70,70
133,female,group C,some college,standard,completed,75,81,84,70
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,70
135,male,group C,bachelor's degree,standard,none,58,55,48,70
136,male,group B,some high school,standard,completed,51,54,41,70
137,male,group E,high school,standard,none,70,55,56,70
138,female,group C,associate's degree,standard,none,59,66,67,70
139,male,group D,some college,standard,completed,71,61,69,70
140,female,group D,some high school,standard,none,76,72,71,70
141,female,group C,some college,free/reduced,none,59,62,64,70
142,female,group E,some college,free/reduced,completed,42,55,54,70
143,male,group A,high school,standard,none,57,43,47,70
144,male,group D,some college,standard,none,88,73,78,70
145,female,group C,some college,free/reduced,none,22,39,33,70
146,male,group B,some high school,standard,none,88,84,75,70
147,male,group C,associate's degree,free/reduced,none,73,68,66,70
148,female,group D,bachelor's degree,standard,completed,68,75,81,70
149,male,group E,associate's degree,free/reduced,completed,100,100,93,70
150,male,group A,some high school,standard,completed,62,67,69,70
151,male,group A,bachelor's degree,standard,none,77,67,68,70
152,female,group B,associate's degree,standard,completed,59,70,66,70
153,male,group D,bachelor's degree,standard,none,54,49,47,70
154,male,group D,some high school,standard,none,62,67,61,70
155,female,group C,some college,standard,completed,70,89,88,70
156,female,group E,high school,free/reduced,completed,66,74,78,70
157,male,group B,some college,free/reduced,none,60,60,60,70
158,female,group B,associate's degree,standard,completed,61,86,87,70
159,male,group D,associate's degree,free/reduced,none,66,62,64,70
160,male,group B,associate's degree,free/reduced,completed,82,78,74,70
161,female,group E,some college,free/reduced,completed,75,88,85,70
162,male,group B,master's degree,free/reduced,none,49,53,52,70
163,male,group C,high school,standard,none,52,53,49,70
164,female,group E,master's degree,standard,none,81,92,91,70
165,female,group C,bachelor's degree,standard,completed,96,100,100,70
166,male,group C,high school,free/reduced,completed,53,51,51,70
167,female,group B,master's degree,free/reduced,completed,58,76,78,70
168,female,group B,high school,standard,completed,68,83,78,70
169,female,group C,some college,free/reduced,completed,67,75,70,70
170,male,group A,high school,standard,completed,72,73,74,70
171,male,group E,some high school,standard,none,94,88,78,70
172,female,group D,some college,standard,none,79,86,81,70
173,female,group C,associate's degree,standard,none,63,67,70,70
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,70
175,female,group C,master's degree,standard,completed,81,91,87,70
176,female,group B,high school,free/reduced,completed,46,54,58,70
177,female,group C,associate's degree,standard,completed,71,77,77,70
178,female,group B,master's degree,free/reduced,completed,52,70,62,70
179,female,group D,some high school,standard,completed,97,100,100,70
180,male,group C,master's degree,free/reduced,completed,62,68,75,70
181,female,group C,some college,free/reduced,none,46,64,66,70
182,female,group E,high school,standard,none,50,50,47,70
183,female,group D,associate's degree,standard,none,65,69,70,70
184,male,group C,some high school,free/reduced,completed,45,52,49,70
185,male,group C,associate's degree,free/reduced,completed,65,67,65,70
186,male,group E,high school,standard,none,80,76,65,70
187,male,group D,some high school,standard,completed,62,66,68,70
188,male,group B,some high school,free/reduced,none,48,52,45,70
189,female,group C,bachelor's degree,standard,none,77,88,87,70
190,female,group E,associate's degree,standard,none,66,65,69,70
191,male,group D,some college,standard,completed,76,83,79,70
192,female,group B,some high school,standard,none,62,64,66,70
193,male,group D,some college,standard,completed,77,62,62,70
194,female,group C,master's degree,standard,completed,69,84,85,70
195,male,group D,associate's degree,standard,none,61,55,52,70
196,male,group C,some high school,free/reduced,completed,59,69,65,70
197,male,group E,high school,free/reduced,none,55,56,51,70
198,female,group B,some college,free/reduced,none,45,53,55,70
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,70
200,female,group C,associate's degree,standard,completed,67,84,86,70
201,female,group D,some college,free/reduced,none,65,81,77,70
202,male,group C,associate's degree,standard,none,69,77,69,70
203,female,group B,associate's degree,standard,none,57,69,68,70
204,male,group C,some college,standard,none,59,41,42,70
205,male,group D,some high school,standard,completed,74,71,78,70
206,male,group E,bachelor's degree,standard,none,82,62,62,70
207,male,group E,high school,standard,completed,81,80,76,70
208,female,group B,some college,free/reduced,none,74,81,76,70
209,female,group B,some college,free/reduced,none,58,61,66,70
210,male,group D,some high school,free/reduced,completed,80,79,79,70
211,male,group C,some college,free/reduced,none,35,28,27,70
212,female,group C,high school,free/reduced,none,42,62,60,70
213,male,group C,associate's degree,free/reduced,completed,60,51,56,70
214,male,group E,high school,standard,completed,87,91,81,70
215,male,group B,some high school,standard,completed,84,83,75,70
216,female,group E,associate's degree,free/reduced,completed,83,86,88,70
217,female,group C,high school,free/reduced,none,34,42,39,70
218,male,group B,high school,free/reduced,none,66,77,70,70
219,male,group B,some high school,standard,completed,61,56,56,70
220,female,group D,high school,standard,completed,56,68,74,70
221,male,group B,associate's degree,standard,none,87,85,73,70
222,female,group C,some high school,free/reduced,none,55,65,62,70
223,male,group D,some high school,standard,none,86,80,75,70
224,female,group B,associate's degree,standard,completed,52,66,73,70
225,female,group E,master's degree,free/reduced,none,45,56,54,70
226,female,group C,some college,standard,none,72,72,71,70
227,male,group D,high school,standard,none,57,50,54,70
228,male,group A,some high school,free/reduced,none,68,72,64,70
229,female,group C,some college,standard,completed,88,95,94,70
230,male,group D,some college,standard,none,76,64,66,70
231,male,group C,associate's degree,standard,none,46,43,42,70
232,female,group B,bachelor's degree,standard,none,67,86,83,70
233,male,group E,some high school,standard,none,92,87,78,70
234,male,group C,bachelor's degree,standard,completed,83,82,84,70
235,male,group D,associate's degree,standard,none,80,75,77,70
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,70
237,female,group D,some high school,standard,completed,64,60,74,70
238,male,group B,some college,standard,none,54,52,51,70
239,male,group C,associate's degree,standard,none,84,80,80,70
240,male,group D,high school,free/reduced,completed,73,68,66,70
241,female,group E,bachelor's degree,standard,none,80,83,83,70
242,female,group D,high school,standard,none,56,52,55,70
243,male,group E,some college,standard,none,59,51,43,70
244,male,group D,some high school,standard,none,75,74,69,70
245,male,group C,associate's degree,standard,none,85,76,71,70
246,male,group E,associate's degree,standard,none,89,76,74,70
247,female,group B,high school,standard,completed,58,70,68,70
248,female,group B,high school,standard,none,65,64,62,70
249,male,group C,high school,standard,none,68,60,53,70
250,male,group A,some high school,standard,completed,47,49,49,70
251,female,group D,some college,free/reduced,none,71,83,83,70
252,female,group B,some high school,standard,completed,60,70,70,70
253,male,group D,master's degree,standard,none,80,80,72,70
254,male,group D,high school,standard,none,54,52,52,70
255,female,group E,some college,standard,none,62,73,70,70
256,female,group C,associate's degree,free/reduced,none,64,73,68,70
257,male,group C,associate's degree,standard,completed,78,77,77,70
258,female,group B,some college,standard,none,70,75,78,70
259,female,group C,master's degree,free/reduced,completed,65,81,81,70
260,female,group C,some high school,free/reduced,completed,64,79,77,70
261,male,group C,some college,standard,completed,79,79,78,70
262,female,group C,some high school,free/reduced,none,44,50,51,70
263,female,group E,high school,standard,none,99,93,90,70
264,male,group D,high school,standard,none,76,73,68,70
265,male,group D,some high school,free/reduced,none,59,42,41,70
266,female,group C,bachelor's degree,standard,none,63,75,81,70
267,female,group D,high school,standard,none,69,72,77,70
268,female,group D,associate's degree,standard,completed,88,92,95,70
269,female,group E,some college,free/reduced,none,71,76,70,70
270,male,group C,bachelor's degree,standard,none,69,63,61,70
271,male,group C,some college,standard,none,58,49,42,70
272,female,group D,associate's degree,free/reduced,none,47,53,58,70
273,female,group D,some college,standard,none,65,70,71,70
274,male,group B,some college,standard,completed,88,85,76,70
275,male,group C,bachelor's degree,standard,none,83,78,73,70
276,female,group C,some high school,standard,completed,85,92,93,70
277,female,group E,high school,standard,completed,59,63,75,70
278,female,group C,some high school,free/reduced,none,65,86,80,70
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,70
280,male,group D,high school,standard,none,53,52,42,70
281,male,group D,high school,standard,none,45,48,46,70
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,70
283,female,group D,some college,free/reduced,completed,70,78,78,70
284,female,group B,some high school,standard,none,37,46,46,70
285,male,group B,associate's degree,standard,completed,81,82,82,70
286,male,group E,associate's degree,standard,completed,97,82,88,70
287,female,group B,some high school,standard,none,67,89,82,70
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,70
289,male,group E,some high school,standard,completed,77,76,77,70
290,male,group C,associate's degree,standard,none,76,70,68,70
291,male,group D,some high school,standard,none,86,73,70,70
292,male,group C,some high school,standard,completed,63,60,57,70
293,female,group E,bachelor's degree,standard,none,65,73,75,70
294,male,group D,high school,free/reduced,completed,78,77,80,70
295,male,group B,associate's degree,free/reduced,none,67,62,60,70
296,male,group A,some high school,standard,completed,46,41,43,70
297,male,group E,associate's degree,standard,completed,71,74,68,70
298,male,group C,high school,free/reduced,completed,40,46,50,70
299,male,group D,associate's degree,free/reduced,none,90,87,75,70
300,male,group A,some college,free/reduced,completed,81,78,81,70
301,male,group D,some high school,free/reduced,none,56,54,52,70
302,female,group C,associate's degree,standard,completed,67,84,81,70
303,male,group B,associate's degree,standard,none,80,76,64,70
304,female,group C,associate's degree,standard,completed,74,75,83,70
305,male,group A,some college,standard,none,69,67,69,70
306,male,group E,some college,standard,completed,99,87,81,70
307,male,group C,some high school,standard,none,51,52,44,70
308,female,group B,associate's degree,free/reduced,none,53,71,67,70
309,female,group D,high school,free/reduced,none,49,57,52,70
310,female,group B,associate's degree,standard,none,73,76,80,70
311,male,group B,bachelor's degree,standard,none,66,60,57,70
312,male,group D,bachelor's degree,standard,completed,67,61,68,70
313,female,group C,associate's degree,free/reduced,completed,68,67,69,70
314,female,group C,bachelor's degree,standard,completed,59,64,75,70
315,male,group C,high school,standard,none,71,66,65,70
316,female,group D,master's degree,standard,completed,77,82,91,70

# Adding a new column with an array

In [111]:
import numpy as np

In [119]:
#create an array of 1000 elements
language_score=np.arange(0,1000)

In [127]:
#adding a new column to dataframe with an array
df_exam['language score']=np.random.randint(0,100, size=len(df_exam))
df_exam

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,langauage,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70,58
1,female,group C,some college,standard,completed,69,90,88,70,62
2,female,group B,master's degree,standard,none,90,95,93,70,50
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,67
4,male,group C,some college,standard,none,76,78,75,70,95
5,female,group B,associate's degree,standard,none,71,83,78,70,63
6,female,group B,some college,standard,completed,88,95,92,70,70
7,male,group B,some college,free/reduced,none,40,43,39,70,93
8,male,group D,high school,free/reduced,completed,64,64,67,70,53
9,female,group B,high school,free/reduced,none,38,60,50,70,19
10,male,group C,associate's degree,standard,none,58,54,52,70,94
11,male,group D,associate's degree,standard,none,40,52,43,70,87
12,female,group B,high school,standard,none,65,81,73,70,6
13,male,group A,some college,standard,completed,78,72,70,70,15
14,female,group A,master's degree,standard,none,50,53,58,70,64
15,female,group C,some high school,standard,none,69,75,78,70,39
16,male,group C,high school,standard,none,88,89,86,70,78
17,female,group B,some high school,free/reduced,none,18,32,28,70,29
18,male,group C,master's degree,free/reduced,completed,46,42,46,70,31
19,female,group C,associate's degree,free/reduced,none,54,58,61,70,62
20,male,group D,high school,standard,none,66,69,63,70,14
21,female,group B,some college,free/reduced,completed,65,75,70,70,62
22,male,group D,some college,standard,none,44,54,53,70,62
23,female,group C,some high school,standard,none,69,73,73,70,20
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,70,85
25,male,group A,master's degree,free/reduced,none,73,74,72,70,89
26,male,group B,some college,standard,none,69,54,55,70,96
27,female,group C,bachelor's degree,standard,none,67,69,75,70,14
28,male,group C,high school,standard,none,70,70,65,70,69
29,female,group D,master's degree,standard,none,62,70,75,70,3
30,female,group D,some college,standard,none,69,74,74,70,52
31,female,group B,some college,standard,none,63,65,61,70,24
32,female,group E,master's degree,free/reduced,none,56,72,65,70,62
33,male,group D,some college,standard,none,40,42,38,70,56
34,male,group E,some college,standard,none,97,87,82,70,98
35,male,group E,associate's degree,standard,completed,81,81,79,70,2
36,female,group D,associate's degree,standard,none,74,81,83,70,1
37,female,group D,some high school,free/reduced,none,50,64,59,70,24
38,female,group D,associate's degree,free/reduced,completed,75,90,88,70,36
39,male,group B,associate's degree,free/reduced,none,57,56,57,70,94
40,male,group C,associate's degree,free/reduced,none,55,61,54,70,48
41,female,group C,associate's degree,standard,none,58,73,68,70,43
42,female,group B,associate's degree,standard,none,53,58,65,70,83
43,male,group B,some college,free/reduced,completed,59,65,66,70,78
44,female,group E,associate's degree,free/reduced,none,50,56,54,70,66
45,male,group B,associate's degree,standard,none,65,54,57,70,99
46,female,group A,associate's degree,standard,completed,55,65,62,70,37
47,female,group C,high school,standard,none,66,71,76,70,37
48,female,group D,associate's degree,free/reduced,completed,57,74,76,70,20
49,male,group C,high school,standard,completed,82,84,82,70,51
50,male,group E,some college,standard,none,53,55,48,70,73
51,male,group E,associate's degree,free/reduced,completed,77,69,68,70,10
52,male,group C,some college,standard,none,53,44,42,70,59
53,male,group D,high school,standard,none,88,78,75,70,46
54,female,group C,some high school,free/reduced,completed,71,84,87,70,91
55,female,group C,high school,free/reduced,none,33,41,43,70,66
56,female,group E,associate's degree,standard,completed,82,85,86,70,63
57,male,group D,associate's degree,standard,none,52,55,49,70,85
58,male,group D,some college,standard,completed,58,59,58,70,33
59,female,group C,some high school,free/reduced,none,0,17,10,70,49
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,70,28
61,male,group A,some high school,free/reduced,none,39,39,34,70,36
62,male,group A,associate's degree,free/reduced,none,62,61,55,70,32
63,female,group C,associate's degree,standard,none,69,80,71,70,21
64,female,group D,some high school,standard,none,59,58,59,70,92
65,male,group B,some high school,standard,none,67,64,61,70,3
66,male,group D,some high school,free/reduced,none,45,37,37,70,69
67,female,group C,some college,standard,none,60,72,74,70,32
68,male,group B,associate's degree,free/reduced,none,61,58,56,70,70
69,female,group C,associate's degree,standard,none,39,64,57,70,95
70,female,group D,some college,free/reduced,completed,58,63,73,70,15
71,male,group D,some college,standard,completed,63,55,63,70,8
72,female,group A,associate's degree,free/reduced,none,41,51,48,70,7
73,male,group C,some high school,free/reduced,none,61,57,56,70,25
74,male,group C,some high school,standard,none,49,49,41,70,16
75,male,group B,associate's degree,free/reduced,none,44,41,38,70,23
76,male,group E,some high school,standard,none,30,26,22,70,52
77,male,group A,bachelor's degree,standard,completed,80,78,81,70,34
78,female,group D,some high school,standard,completed,61,74,72,70,36
79,female,group E,master's degree,standard,none,62,68,68,70,95
80,female,group B,associate's degree,standard,none,47,49,50,70,46
81,male,group B,high school,free/reduced,none,49,45,45,70,15
82,male,group A,some college,free/reduced,completed,50,47,54,70,18
83,male,group E,associate's degree,standard,none,72,64,63,70,66
84,male,group D,high school,free/reduced,none,42,39,34,70,71
85,female,group C,some college,standard,none,73,80,82,70,48
86,female,group C,some college,free/reduced,none,76,83,88,70,7
87,female,group D,associate's degree,standard,none,71,71,74,70,0
88,female,group A,some college,standard,none,58,70,67,70,46
89,female,group D,some high school,standard,none,73,86,82,70,7
90,female,group C,bachelor's degree,standard,none,65,72,74,70,64
91,male,group C,high school,free/reduced,none,27,34,36,70,79
92,male,group C,high school,standard,none,71,79,71,70,44
93,male,group C,associate's degree,free/reduced,completed,43,45,50,70,48
94,female,group B,some college,standard,none,79,86,92,70,0
95,male,group C,associate's degree,free/reduced,completed,78,81,82,70,74
96,male,group B,some high school,standard,completed,65,66,62,70,65
97,female,group E,some college,standard,completed,63,72,70,70,11
98,female,group D,some college,free/reduced,none,58,67,62,70,97
99,female,group D,bachelor's degree,standard,none,65,67,62,70,77
100,male,group B,some college,standard,none,79,67,67,70,9
101,male,group D,bachelor's degree,standard,completed,68,74,74,70,86
102,female,group D,associate's degree,standard,none,85,91,89,70,5
103,male,group B,high school,standard,completed,60,44,47,70,73
104,male,group C,some college,standard,completed,98,86,90,70,11
105,female,group C,some college,standard,none,58,67,72,70,44
106,female,group D,master's degree,standard,none,87,100,100,70,25
107,male,group E,associate's degree,standard,completed,66,63,64,70,84
108,female,group B,associate's degree,free/reduced,none,52,76,70,70,47
109,female,group B,some high school,standard,none,70,64,72,70,44
110,female,group D,associate's degree,free/reduced,completed,77,89,98,70,89
111,male,group C,high school,standard,none,62,55,49,70,39
112,male,group A,associate's degree,standard,none,54,53,47,70,9
113,female,group D,some college,standard,none,51,58,54,70,65
114,female,group E,bachelor's degree,standard,completed,99,100,100,70,29
115,male,group C,high school,standard,none,84,77,74,70,25
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,70,20
117,female,group D,bachelor's degree,standard,none,78,82,79,70,41
118,female,group D,some high school,standard,none,51,63,61,70,75
119,female,group C,some college,standard,none,55,69,65,70,36
120,female,group C,bachelor's degree,standard,completed,79,92,89,70,51
121,male,group B,associate's degree,standard,completed,91,89,92,70,81
122,female,group C,some college,standard,completed,88,93,93,70,87
123,male,group D,high school,free/reduced,none,63,57,56,70,43
124,male,group E,some college,standard,none,83,80,73,70,20
125,female,group B,high school,standard,none,87,95,86,70,95
126,male,group B,some high school,standard,none,72,68,67,70,46
127,male,group D,some college,standard,completed,65,77,74,70,50
128,male,group D,master's degree,standard,none,82,82,74,70,75
129,female,group A,bachelor's degree,standard,none,51,49,51,70,80
130,male,group D,master's degree,standard,none,89,84,82,70,40
131,male,group C,some high school,free/reduced,completed,53,37,40,70,46
132,male,group E,some college,free/reduced,completed,87,74,70,70,2
133,female,group C,some college,standard,completed,75,81,84,70,65
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,70,7
135,male,group C,bachelor's degree,standard,none,58,55,48,70,90
136,male,group B,some high school,standard,completed,51,54,41,70,68
137,male,group E,high school,standard,none,70,55,56,70,15
138,female,group C,associate's degree,standard,none,59,66,67,70,51
139,male,group D,some college,standard,completed,71,61,69,70,23
140,female,group D,some high school,standard,none,76,72,71,70,21
141,female,group C,some college,free/reduced,none,59,62,64,70,96
142,female,group E,some college,free/reduced,completed,42,55,54,70,96
143,male,group A,high school,standard,none,57,43,47,70,81
144,male,group D,some college,standard,none,88,73,78,70,18
145,female,group C,some college,free/reduced,none,22,39,33,70,23
146,male,group B,some high school,standard,none,88,84,75,70,86
147,male,group C,associate's degree,free/reduced,none,73,68,66,70,58
148,female,group D,bachelor's degree,standard,completed,68,75,81,70,25
149,male,group E,associate's degree,free/reduced,completed,100,100,93,70,36
150,male,group A,some high school,standard,completed,62,67,69,70,74
151,male,group A,bachelor's degree,standard,none,77,67,68,70,77
152,female,group B,associate's degree,standard,completed,59,70,66,70,29
153,male,group D,bachelor's degree,standard,none,54,49,47,70,24
154,male,group D,some high school,standard,none,62,67,61,70,71
155,female,group C,some college,standard,completed,70,89,88,70,81
156,female,group E,high school,free/reduced,completed,66,74,78,70,26
157,male,group B,some college,free/reduced,none,60,60,60,70,19
158,female,group B,associate's degree,standard,completed,61,86,87,70,54
159,male,group D,associate's degree,free/reduced,none,66,62,64,70,34
160,male,group B,associate's degree,free/reduced,completed,82,78,74,70,29
161,female,group E,some college,free/reduced,completed,75,88,85,70,23
162,male,group B,master's degree,free/reduced,none,49,53,52,70,45
163,male,group C,high school,standard,none,52,53,49,70,3
164,female,group E,master's degree,standard,none,81,92,91,70,75
165,female,group C,bachelor's degree,standard,completed,96,100,100,70,16
166,male,group C,high school,free/reduced,completed,53,51,51,70,74
167,female,group B,master's degree,free/reduced,completed,58,76,78,70,26
168,female,group B,high school,standard,completed,68,83,78,70,10
169,female,group C,some college,free/reduced,completed,67,75,70,70,47
170,male,group A,high school,standard,completed,72,73,74,70,13
171,male,group E,some high school,standard,none,94,88,78,70,92
172,female,group D,some college,standard,none,79,86,81,70,71
173,female,group C,associate's degree,standard,none,63,67,70,70,40
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,70,55
175,female,group C,master's degree,standard,completed,81,91,87,70,81
176,female,group B,high school,free/reduced,completed,46,54,58,70,72
177,female,group C,associate's degree,standard,completed,71,77,77,70,54
178,female,group B,master's degree,free/reduced,completed,52,70,62,70,21
179,female,group D,some high school,standard,completed,97,100,100,70,82
180,male,group C,master's degree,free/reduced,completed,62,68,75,70,67
181,female,group C,some college,free/reduced,none,46,64,66,70,17
182,female,group E,high school,standard,none,50,50,47,70,82
183,female,group D,associate's degree,standard,none,65,69,70,70,16
184,male,group C,some high school,free/reduced,completed,45,52,49,70,95
185,male,group C,associate's degree,free/reduced,completed,65,67,65,70,86
186,male,group E,high school,standard,none,80,76,65,70,84
187,male,group D,some high school,standard,completed,62,66,68,70,41
188,male,group B,some high school,free/reduced,none,48,52,45,70,1
189,female,group C,bachelor's degree,standard,none,77,88,87,70,55
190,female,group E,associate's degree,standard,none,66,65,69,70,49
191,male,group D,some college,standard,completed,76,83,79,70,27
192,female,group B,some high school,standard,none,62,64,66,70,63
193,male,group D,some college,standard,completed,77,62,62,70,35
194,female,group C,master's degree,standard,completed,69,84,85,70,12
195,male,group D,associate's degree,standard,none,61,55,52,70,68
196,male,group C,some high school,free/reduced,completed,59,69,65,70,43
197,male,group E,high school,free/reduced,none,55,56,51,70,43
198,female,group B,some college,free/reduced,none,45,53,55,70,26
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,70,81
200,female,group C,associate's degree,standard,completed,67,84,86,70,20
201,female,group D,some college,free/reduced,none,65,81,77,70,49
202,male,group C,associate's degree,standard,none,69,77,69,70,62
203,female,group B,associate's degree,standard,none,57,69,68,70,0
204,male,group C,some college,standard,none,59,41,42,70,36
205,male,group D,some high school,standard,completed,74,71,78,70,21
206,male,group E,bachelor's degree,standard,none,82,62,62,70,87
207,male,group E,high school,standard,completed,81,80,76,70,37
208,female,group B,some college,free/reduced,none,74,81,76,70,75
209,female,group B,some college,free/reduced,none,58,61,66,70,30
210,male,group D,some high school,free/reduced,completed,80,79,79,70,95
211,male,group C,some college,free/reduced,none,35,28,27,70,28
212,female,group C,high school,free/reduced,none,42,62,60,70,9
213,male,group C,associate's degree,free/reduced,completed,60,51,56,70,4
214,male,group E,high school,standard,completed,87,91,81,70,74
215,male,group B,some high school,standard,completed,84,83,75,70,95
216,female,group E,associate's degree,free/reduced,completed,83,86,88,70,33
217,female,group C,high school,free/reduced,none,34,42,39,70,25
218,male,group B,high school,free/reduced,none,66,77,70,70,52
219,male,group B,some high school,standard,completed,61,56,56,70,85
220,female,group D,high school,standard,completed,56,68,74,70,25
221,male,group B,associate's degree,standard,none,87,85,73,70,2
222,female,group C,some high school,free/reduced,none,55,65,62,70,63
223,male,group D,some high school,standard,none,86,80,75,70,39
224,female,group B,associate's degree,standard,completed,52,66,73,70,29
225,female,group E,master's degree,free/reduced,none,45,56,54,70,51
226,female,group C,some college,standard,none,72,72,71,70,0
227,male,group D,high school,standard,none,57,50,54,70,54
228,male,group A,some high school,free/reduced,none,68,72,64,70,2
229,female,group C,some college,standard,completed,88,95,94,70,11
230,male,group D,some college,standard,none,76,64,66,70,34
231,male,group C,associate's degree,standard,none,46,43,42,70,42
232,female,group B,bachelor's degree,standard,none,67,86,83,70,79
233,male,group E,some high school,standard,none,92,87,78,70,28
234,male,group C,bachelor's degree,standard,completed,83,82,84,70,83
235,male,group D,associate's degree,standard,none,80,75,77,70,3
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,70,96
237,female,group D,some high school,standard,completed,64,60,74,70,54
238,male,group B,some college,standard,none,54,52,51,70,7
239,male,group C,associate's degree,standard,none,84,80,80,70,74
240,male,group D,high school,free/reduced,completed,73,68,66,70,7
241,female,group E,bachelor's degree,standard,none,80,83,83,70,51
242,female,group D,high school,standard,none,56,52,55,70,97
243,male,group E,some college,standard,none,59,51,43,70,26
244,male,group D,some high school,standard,none,75,74,69,70,39
245,male,group C,associate's degree,standard,none,85,76,71,70,85
246,male,group E,associate's degree,standard,none,89,76,74,70,44
247,female,group B,high school,standard,completed,58,70,68,70,7
248,female,group B,high school,standard,none,65,64,62,70,0
249,male,group C,high school,standard,none,68,60,53,70,81
250,male,group A,some high school,standard,completed,47,49,49,70,97
251,female,group D,some college,free/reduced,none,71,83,83,70,23
252,female,group B,some high school,standard,completed,60,70,70,70,2
253,male,group D,master's degree,standard,none,80,80,72,70,63
254,male,group D,high school,standard,none,54,52,52,70,76
255,female,group E,some college,standard,none,62,73,70,70,16
256,female,group C,associate's degree,free/reduced,none,64,73,68,70,10
257,male,group C,associate's degree,standard,completed,78,77,77,70,62
258,female,group B,some college,standard,none,70,75,78,70,88
259,female,group C,master's degree,free/reduced,completed,65,81,81,70,29
260,female,group C,some high school,free/reduced,completed,64,79,77,70,49
261,male,group C,some college,standard,completed,79,79,78,70,48
262,female,group C,some high school,free/reduced,none,44,50,51,70,52
263,female,group E,high school,standard,none,99,93,90,70,31
264,male,group D,high school,standard,none,76,73,68,70,24
265,male,group D,some high school,free/reduced,none,59,42,41,70,96
266,female,group C,bachelor's degree,standard,none,63,75,81,70,68
267,female,group D,high school,standard,none,69,72,77,70,43
268,female,group D,associate's degree,standard,completed,88,92,95,70,62
269,female,group E,some college,free/reduced,none,71,76,70,70,90
270,male,group C,bachelor's degree,standard,none,69,63,61,70,92
271,male,group C,some college,standard,none,58,49,42,70,66
272,female,group D,associate's degree,free/reduced,none,47,53,58,70,67
273,female,group D,some college,standard,none,65,70,71,70,6
274,male,group B,some college,standard,completed,88,85,76,70,89
275,male,group C,bachelor's degree,standard,none,83,78,73,70,27
276,female,group C,some high school,standard,completed,85,92,93,70,9
277,female,group E,high school,standard,completed,59,63,75,70,88
278,female,group C,some high school,free/reduced,none,65,86,80,70,60
279,male,group B,bachelor's degree,free/reduced,none,73,56,57,70,30
280,male,group D,high school,standard,none,53,52,42,70,82
281,male,group D,high school,standard,none,45,48,46,70,40
282,female,group D,bachelor's degree,free/reduced,none,73,79,84,70,98
283,female,group D,some college,free/reduced,completed,70,78,78,70,98
284,female,group B,some high school,standard,none,37,46,46,70,2
285,male,group B,associate's degree,standard,completed,81,82,82,70,97
286,male,group E,associate's degree,standard,completed,97,82,88,70,63
287,female,group B,some high school,standard,none,67,89,82,70,92
288,male,group B,bachelor's degree,free/reduced,none,88,75,76,70,91
289,male,group E,some high school,standard,completed,77,76,77,70,5
290,male,group C,associate's degree,standard,none,76,70,68,70,12
291,male,group D,some high school,standard,none,86,73,70,70,85
292,male,group C,some high school,standard,completed,63,60,57,70,35
293,female,group E,bachelor's degree,standard,none,65,73,75,70,33
294,male,group D,high school,free/reduced,completed,78,77,80,70,91
295,male,group B,associate's degree,free/reduced,none,67,62,60,70,75
296,male,group A,some high school,standard,completed,46,41,43,70,23
297,male,group E,associate's degree,standard,completed,71,74,68,70,37
298,male,group C,high school,free/reduced,completed,40,46,50,70,79
299,male,group D,associate's degree,free/reduced,none,90,87,75,70,67
300,male,group A,some college,free/reduced,completed,81,78,81,70,65
301,male,group D,some high school,free/reduced,none,56,54,52,70,28
302,female,group C,associate's degree,standard,completed,67,84,81,70,55

In [133]:
#create random float numbers between 1 and 100
np.random.uniform(0,100,size=len(df_exam))

array([59.56751577, 89.79499545, 77.99694129,  0.55851071, 64.21597414,
       46.85590473, 45.66837909, 41.81991138, 74.87109435, 39.87982736,
       47.23723939, 50.99609628, 68.77864924, 82.87765616, 74.52454619,
       79.79807165, 12.49196558, 80.50480489, 92.80780822, 70.54707814,
       34.90614745, 64.27321425, 56.6174982 , 83.84835234, 49.75580667,
       32.73049215, 36.33290356, 28.38678217, 67.18410953, 92.35015531,
       10.40475591, 25.79457298, 87.40471113, 11.48893687, 18.87776697,
       63.62124461, 48.26521833, 86.67329222, 61.57405974, 86.18803083,
        9.54230297, 69.79959568, 57.46350982,  6.8662876 , 96.69390753,
       25.09618336, 53.79844017, 68.6293276 , 35.82318927, 77.27692535,
       53.62829691, 41.57641617, 91.52025174, 84.58462725, 37.64499782,
       84.78415222, 53.75248734, 88.81360694, 15.33595241, 77.53908769,
       46.38370138, 86.94923117, 28.50755326, 18.84532425, 46.67760125,
       39.35915953, 32.79234419, 81.30903555, 99.14873498, 42.07103739,
       85.69810324, 71.24961004,  9.86322732, 94.96320199, 29.5064204 ,
        2.38119261, 71.88415179, 88.82379953, 96.38638013, 40.97575433,
       17.48565045, 66.96245056, 91.29815117, 58.97556812, 11.55217212,
       15.72010191, 18.48300503, 97.3770253 , 27.06503403, 43.23788698,
       37.37343193, 58.58646717,  7.75007251, 66.14396535, 23.32265339,
       14.52886955, 15.8809686 , 17.41745953,  7.49962867, 12.37025698,
       39.008182  , 13.62439423, 56.2816205 , 95.08510316, 72.0128087 ,
       10.0479478 , 47.4071264 , 34.93058242, 60.9589095 ,  5.85328242,
       35.33958395, 75.78705941,  9.26667919, 14.74130742,  7.59787834,
        3.71084467, 86.9658197 ,  1.59839584, 24.24430532, 79.56792134,
       73.94911366, 28.0531946 , 54.53226133, 97.03231888, 15.8997797 ,
       44.35094419, 93.89578195, 71.35083221, 69.53882683, 52.78840448,
        8.47048318, 76.71158456, 55.33395651, 38.71813755, 74.92019879,
       37.99769023, 50.02934419, 31.26659912, 33.20203097,  4.24621193,
       28.94520869, 59.11481028, 18.7480955 , 85.46105845, 50.16571962,
       81.39033712, 40.11386806, 50.84159285,  6.28667983,  2.04683159,
       66.79339559, 31.95264275, 41.92014833, 21.53819803, 18.33578485,
        8.76456338, 78.86135851, 39.24378967,  8.72321263, 47.65091513,
       14.14393716,  2.09562768, 91.16456717, 15.69744362, 35.44481032,
       81.99696926, 45.61472593, 51.17008895, 68.15366951, 86.16495413,
       28.53839853, 48.7012971 , 30.51982867, 13.67571488, 11.80215098,
       81.311635  ,  3.40955301, 92.3839992 , 36.97542848, 94.71922979,
       31.33711025, 68.90749949, 85.38120504, 86.92689517,  4.31006021,
       10.18194745, 92.69733989, 34.85082723, 66.14366833, 30.08093384,
       61.2410233 , 94.88721952, 14.14980113, 67.34553014, 81.59262941,
       99.86152426, 69.790492  , 76.48270178, 64.59810216, 58.39147355,
       60.10306614, 21.84143881, 25.57584073, 58.32743896, 35.74923034,
       77.34427214, 24.58053456, 96.99764408,  1.76327911, 79.12097533,
       58.88501516, 97.407686  ,  4.84489438, 21.50375985, 14.85512322,
        2.17423684,  4.11042513, 33.60340354, 58.83893223, 14.87448426,
        0.67179006, 85.27301161, 88.38963627, 71.341592  , 60.07184698,
       75.44170205, 29.59186847,  8.16860886, 81.6547961 , 46.61915733,
       77.48867448, 68.52290105, 14.99078297, 56.27501834, 38.23417863,
       89.11643878, 74.18431486, 95.52370679, 75.3179395 , 98.89610745,
       27.99857911, 82.10870601, 46.89928505,  6.27094957, 70.473569  ,
       98.55804004, 44.80303047, 14.45495896, 43.37928626, 48.76350481,
       18.32650057, 34.27284517, 81.70525239,  6.71548632, 39.06012054,
       61.86655293,  7.46211139, 21.78152496, 77.70241867, 28.11358794,
       60.05702496, 84.22793351, 52.54761907, 27.72600335,  8.8231147 ,
       83.39195082, 76.46323787,  7.98078938, 80.15645733, 33.83212165,
       22.90645667, 44.41046122, 22.74245496, 17.39308872, 10.0839082 ,
       49.53574027, 12.67794986, 25.65579914, 53.23672012,  3.57979135,
       12.48214079, 48.73734609, 38.00359739, 96.63826241, 55.28324599,
       89.5385084 , 25.7568394 , 76.76305131, 11.05138563, 21.24403758,
       56.05716144, 15.24125229, 81.1483269 , 19.63420971, 77.58916793,
        8.54355093, 21.56802079, 92.34796503, 65.27835954, 36.31624809,
       79.81374989, 99.97516043, 71.07668899, 68.51470199, 20.20562476,
        7.98038764, 59.98889975, 84.32170409, 64.64824016, 70.35217156,
       33.60783525, 29.46713297, 77.50053062, 64.65933557, 59.69040318,
       23.58986306, 47.93873546, 25.69779012, 10.05902398, 80.45701574,
       98.97801647, 79.073593  ,  6.52922662, 77.46759224, 47.16046201,
       54.62457698, 70.26510394, 13.41409836, 13.72251582, 86.84659103,
        7.57817467, 96.89778733, 91.1315319 , 75.41718577, 32.84338378,
       66.39271654, 83.92784601, 49.71115003, 55.45889932,  3.51332495,
       30.3094432 ,  5.37207003, 76.40336125, 14.85349101, 30.54438308,
       97.15727182, 17.31005995, 61.86631861, 23.85661816, 49.76892081,
       56.85167221,  3.63449179, 16.95402696, 38.17529525, 77.29714033,
       81.49114433, 22.51061643, 27.90267912,  8.25426628, 72.07236885,
       34.74389768, 12.68065401, 45.05300776, 41.20043156, 95.46335611,
       81.747499  , 66.38163405, 70.25923843,  1.82080127, 87.91020275,
       70.8516982 , 67.79055693, 48.30084491, 50.1745398 , 80.68281155,
       24.93121243,  4.40594593, 48.17116683, 41.58356289,  3.24235067,
       73.18359683, 89.03268773, 25.86299428, 20.93130741,  5.12392712,
       88.76883487, 27.71141633, 20.90121135, 48.90728656, 88.21369162,
       57.28303524,  3.90534297, 11.46374138, 72.19023899, 61.97388552,
       20.96526514, 56.98219344, 32.34973604, 90.11859153, 85.08478259,
       61.81340355, 72.89354716, 49.58450383, 78.53288485, 21.67728255,
       91.68275314, 63.58391159, 25.78162845, 38.327161  , 22.92887783,
       42.27090597, 34.63080664, 60.55655876, 98.92375292, 61.09549291,
        4.95928513, 19.73984347, 74.53867635, 62.58507964, 37.85682414,
       19.74669039, 69.13130523, 59.4654422 , 39.3124573 , 55.55930456,
       33.50623667, 93.88819698, 77.51240021, 21.22549893, 15.94142278,
       63.8170628 , 35.25234706, 20.67047728, 25.1814787 , 61.92770794,
       85.09482652, 39.12650526,  0.9842978 , 94.97149935, 98.28513448,
       88.51787719, 92.25141566, 76.54692757,  2.48293827, 42.30296652,
       16.73510926, 65.9925127 , 10.65911032, 52.54867524, 77.05028788,
       35.35920945, 17.80661885, 84.63508834, 52.9725284 , 69.7579568 ,
       36.57681516, 15.62496526, 89.96437287, 46.17427022, 45.81251935,
       80.54045699, 98.36305818, 38.16626711, 39.74149768,  3.33762896,
       45.89336635, 30.08042097, 29.03301192, 39.47002298, 92.43860357,
       79.01110219, 61.63210901,  7.74921934, 27.81045776, 97.1967653 ,
       95.80320996, 27.34899109, 29.90539381, 40.41971529, 85.59845084,
       84.11986193, 74.01975835, 45.62358868, 22.74753877, 58.85386814,
       24.31333455, 18.33796626, 59.33468404, 17.92579186,  6.34079421,
       73.97938483, 87.88841523, 20.62167341, 34.15961865,  9.72766649,
       84.25414269, 73.09122079, 88.69523081,  1.07609704, 10.06514158,
       11.7121005 , 56.32447269, 64.17279561, 46.06781192, 34.36923979,
       95.28414057, 38.96663174, 98.93283394, 82.29978911, 92.30863365,
        1.83227827, 92.04843336, 90.38179869, 17.76045301, 33.68529535,
       62.24036292, 99.13665209, 86.03858717, 60.22794239, 96.17411856,
       77.00980187, 56.88716084, 66.10849655, 19.78819042, 72.54278918,
       54.19775219, 15.36094528, 86.69131918, 59.76437811,  8.91331907,
       35.16569127, 97.05181062, 40.43521149, 28.50280028, 92.30491328,
       12.86990251, 57.59690072, 37.04899196, 82.46979484, 24.62231943,
       92.54158332, 78.20624286, 72.26415347, 44.76107599, 22.01633497,
       79.60784117, 84.96132894, 16.38974026, 45.25952393, 35.57516683,
        6.35987775,  5.34949683,  0.30463244, 18.95786714, 28.83380798,
       54.78703752, 68.49644112, 79.69453455, 63.85320232, 17.03812643,
       66.97908115, 41.52183068, 48.07539882, 94.24551218, 75.24231123,
       46.70605671, 30.83344573, 66.49032489, 93.44437453, 14.26910032,
        6.61932434, 10.91452892, 97.43213402, 11.7305126 , 45.08454198,
       18.20184788, 19.4059616 , 76.25684574, 68.5003665 , 82.40444782,
       72.32492145, 13.67438658, 38.28176385, 11.25583539, 90.976064  ,
       22.82706134, 83.68728652, 59.12498452,  1.03998086, 93.85770772,
        9.75246435, 16.9883578 , 46.4431831 , 71.75855993, 21.40782255,
        9.74174274, 19.95855042, 27.83414127, 30.16710203, 24.06778838,
       56.87046253, 14.87119997,  0.31532908, 34.32542737, 78.20041262,
       84.22272954, 55.50523933, 21.20345792, 16.28084788, 99.22565717,
       48.64253129, 83.05968267, 83.74451798, 93.74413645, 16.28757192,
       10.17967382, 83.98543107, 33.09251509, 44.92270179, 53.55780464,
       87.5718069 , 62.65180044, 46.4172262 , 31.38834101, 86.59988726,
       79.40881996, 75.98109776, 41.32852474, 14.74073793, 23.48440513,
       41.19864996, 55.89698939, 93.22936964, 88.30733496, 99.25409573,
       56.99545199, 26.66604504, 74.07851781, 99.3866392 , 81.4749767 ,
       56.25737586, 79.28604701, 93.62488192, 71.5954774 , 82.93638958,
       79.90442891, 38.44822472, 14.10103331, 12.63282884, 51.08650696,
       71.04579979, 78.72488758, 41.36360656,  0.57113316, 88.23763336,
       14.28756654,  6.48426   , 20.22206146, 34.06877638, 43.87606154,
       95.39535778, 19.71792194, 44.01031011, 78.44527096, 94.3181917 ,
       66.28613625, 87.34450361, 68.14880778, 67.30633471, 62.59628793,
       89.2279728 , 84.81980865, 88.44600122, 73.86959125, 50.49255895,
       17.63209475, 14.54323215, 89.37065129, 87.10115799, 89.68182283,
       14.81183384, 86.06448703, 87.40477572, 53.30475666, 37.25312518,
       32.11806975, 90.64157817, 30.05783409, 24.65592562,  9.22592892,
        5.09166143, 90.90831015, 92.37540939, 51.54857636, 88.12745957,
       13.43522389,  9.89861889, 63.81790493, 95.35839598, 86.16487292,
       65.13793994, 81.43026997, 43.99385735,  4.02251212, 99.3077512 ,
       68.09365721, 51.26501558, 30.96023944, 86.79136961, 16.8189644 ,
       45.83218354, 83.25379642, 21.47862891, 89.65542683, 11.31043908,
       51.93119924, 21.83081916, 87.47864105, 95.08397432, 98.02020992,
       23.61483863, 54.55362952, 89.44240586, 73.98729853, 32.00995943,
       73.08118754, 22.8395779 , 40.26476021, 77.61473392, 65.1164298 ,
       61.81394587, 34.5793459 , 31.99699305, 21.24544027, 77.56596738,
        6.41112195, 85.34051069, 72.17731536, 57.80014462, 22.35735773,
       93.58781698, 11.50639844, 23.90456281, 47.64598409, 16.95248762,
       70.19107237,  2.68675718, 59.37723053, 95.78153063, 81.82050836,
       47.52145257, 52.62501146,  0.31389911, 28.34234725, 89.82301198,
       99.90132871, 48.56529138, 15.4464949 , 14.8302507 , 29.23396351,
       39.66287247, 30.32813592, 61.97392815, 89.23951126, 36.06396676,
       53.98080223, 33.72237445, 87.35676317,  8.51620112, 54.20075326,
       80.13661498, 39.01475995, 71.23223948,  8.4565093 , 51.18534514,
       65.29394277,  6.4335241 , 96.80604719,  4.68699044, 26.91273828,
       42.24027567, 41.8922172 , 70.66127689, 85.94376392, 19.42547969,
       87.54991925,  1.58742936, 23.60931162, 62.88708479, 22.86640482,
       96.45044772, 78.08307733, 59.81701157, 12.17497192, 21.94686882,
       51.33054079,  8.13758312,  0.96232031,  2.89897994, 55.27932702,
       49.88598456, 31.3592622 , 54.8514455 ,  8.41556653, 63.28535553,
       30.02858104, 89.82667401, 84.91740557, 29.33781026, 69.57118179,
        6.04970737, 38.30235601, 34.53828824, 25.48080847,  9.98547721,
       42.041482  , 84.64034634, 99.19770065, 13.27971127, 83.43704232,
       52.91689355,  6.53623139, 37.51336832, 11.83067249, 87.72357392,
        5.25636033, 60.08410909, 79.75555877, 67.92571372, 77.19196583,
       72.53820013, 83.70209422, 98.21210247, 44.45214172, 49.95329793,
       21.17289642, 37.74810594, 28.39826481, 73.60998009, 54.0300729 ,
       12.48478204, 13.44498008, 40.89553361, 11.41707112, 15.16601935,
       33.24892248, 51.63983889, 57.13868275, 62.25343799, 79.9354656 ,
       94.91171114, 81.9084546 , 71.63280987,  6.35741525, 15.29711634,
       59.75932779, 81.35812051, 50.02839817, 46.38596647,  2.0716141 ,
       45.2860901 , 24.83495707, 42.23945513, 51.08132419, 14.28459708,
       68.58859714,  3.86607158, 97.6280166 , 65.73003005, 25.99471301,
       53.37235872, 35.30247468, 25.49438098, 99.33450221, 30.62786271,
       97.57367503, 36.70293935, 46.12881944, 62.32803133,  4.36556075,
       54.87305879, 10.14290658, 32.54565547, 52.53334667, 86.17202694,
       28.72919281, 99.03693053, 96.02210536, 83.33099546, 52.8958229 ,
       19.48819788, 69.57514066,  3.61288388, 11.82876967, 10.21658808,
       10.18489563, 75.40990353, 25.98867962, 67.22318507, 10.41860519,
       74.40465441, 34.35042884, 72.70948558, 64.91767303, 25.5651981 ,
       19.95526246, 75.80392737, 25.07106707, 81.07308378, 47.363551  ,
       69.24223606, 51.09848862, 43.6984445 ,  2.58376482, 56.93306753,
       10.15323046, 63.77066548, 36.9693741 , 61.95551653, 75.24389287,
       47.55288345, 78.3605074 , 43.76050467, 81.18578061, 51.81100278,
       61.99332891, 53.92296653, 30.57521073, 99.9613032 , 58.32628817,
       90.51794585, 68.7056493 , 98.7466872 , 51.9413808 , 35.4632464 ,
       87.15928351, 39.94474427,  9.44770473, 57.17702016, 90.48859221,
       91.87749171, 76.27382086, 40.73680838, 20.00520785, 17.43126378,
       68.54038186, 59.1233223 , 72.57386092, 62.27298385, 67.67506028,
       90.95853431, 66.50077885, 45.95298351, 44.82834455, 47.53968253,
       38.72963463, 56.17560226, 82.29015749, 36.41116121, 78.55466279,
       90.23151422, 81.42891443, 79.91065341, 96.44347908, 50.7660999 ,
       60.37489659, 34.30181255, 49.05736847, 45.88126886, 44.80066965,
        2.98918236, 85.96683876, 85.13692897, 83.36936427, 43.61258693,
       90.75250441, 71.49280883, 26.97786035, 96.03364317, 52.76325188,
       26.80014534, 63.03331259, 17.94088333, 32.13666173, 55.24431874,
       95.62453743, 30.76480496, 88.07481593, 79.54999565, 96.91700671,
       76.96653875, 64.07477921, 19.41505258, 38.96729351, 33.55120017,
       38.713331  , 79.83756501, 57.8911812 ,  4.39467163, 97.95968281])

# Adding a new column

# Assign()
        when to use
        .Add multiple columns in a single line of code 
        .when you need to overwrite the values of an existing columns
        It returns a new object(a copy) with all the original columns in addition to the new ones

In [141]:
#create random numbers for our new score columns 
score1=np.random.randint(1,100,size=1000)
score2=np.random.randint(1,100,size=1000)

In [145]:
#create a series using the random numbers 
series1=pd.Series(score1, index=np.arange(0,1000))
series2=pd.Series(score2, index=np.arange(0,1000))

In [155]:
#using assign() to add multiple columns
df_exam.assign(score1=series1,score2=series2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,langauage,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,70,58,2,16
1,female,group C,some college,standard,completed,69,90,88,70,62,21,42
2,female,group B,master's degree,standard,none,90,95,93,70,50,6,44
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,67,54,37
4,male,group C,some college,standard,none,76,78,75,70,95,38,39
5,female,group B,associate's degree,standard,none,71,83,78,70,63,65,45
6,female,group B,some college,standard,completed,88,95,92,70,70,90,78
7,male,group B,some college,free/reduced,none,40,43,39,70,93,70,69
8,male,group D,high school,free/reduced,completed,64,64,67,70,53,82,28
9,female,group B,high school,free/reduced,none,38,60,50,70,19,40,39
10,male,group C,associate's degree,standard,none,58,54,52,70,94,71,58
11,male,group D,associate's degree,standard,none,40,52,43,70,87,11,79
12,female,group B,high school,standard,none,65,81,73,70,6,82,88
13,male,group A,some college,standard,completed,78,72,70,70,15,22,21
14,female,group A,master's degree,standard,none,50,53,58,70,64,35,75
15,female,group C,some high school,standard,none,69,75,78,70,39,75,49
16,male,group C,high school,standard,none,88,89,86,70,78,81,11
17,female,group B,some high school,free/reduced,none,18,32,28,70,29,30,74
18,male,group C,master's degree,free/reduced,completed,46,42,46,70,31,44,32
19,female,group C,associate's degree,free/reduced,none,54,58,61,70,62,76,67
20,male,group D,high school,standard,none,66,69,63,70,14,20,90
21,female,group B,some college,free/reduced,completed,65,75,70,70,62,7,26
22,male,group D,some college,standard,none,44,54,53,70,62,10,42
23,female,group C,some high school,standard,none,69,73,73,70,20,34,10
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80,70,85,93,58
25,male,group A,master's degree,free/reduced,none,73,74,72,70,89,38,10
26,male,group B,some college,standard,none,69,54,55,70,96,65,21
27,female,group C,bachelor's degree,standard,none,67,69,75,70,14,54,73
28,male,group C,high school,standard,none,70,70,65,70,69,91,32
29,female,group D,master's degree,standard,none,62,70,75,70,3,21,80
30,female,group D,some college,standard,none,69,74,74,70,52,64,67
31,female,group B,some college,standard,none,63,65,61,70,24,29,8
32,female,group E,master's degree,free/reduced,none,56,72,65,70,62,57,91
33,male,group D,some college,standard,none,40,42,38,70,56,25,74
34,male,group E,some college,standard,none,97,87,82,70,98,17,54
35,male,group E,associate's degree,standard,completed,81,81,79,70,2,27,9
36,female,group D,associate's degree,standard,none,74,81,83,70,1,83,72
37,female,group D,some high school,free/reduced,none,50,64,59,70,24,13,78
38,female,group D,associate's degree,free/reduced,completed,75,90,88,70,36,87,22
39,male,group B,associate's degree,free/reduced,none,57,56,57,70,94,90,7
40,male,group C,associate's degree,free/reduced,none,55,61,54,70,48,75,16
41,female,group C,associate's degree,standard,none,58,73,68,70,43,27,67
42,female,group B,associate's degree,standard,none,53,58,65,70,83,50,44
43,male,group B,some college,free/reduced,completed,59,65,66,70,78,55,94
44,female,group E,associate's degree,free/reduced,none,50,56,54,70,66,86,46
45,male,group B,associate's degree,standard,none,65,54,57,70,99,28,15
46,female,group A,associate's degree,standard,completed,55,65,62,70,37,92,21
47,female,group C,high school,standard,none,66,71,76,70,37,97,22
48,female,group D,associate's degree,free/reduced,completed,57,74,76,70,20,58,88
49,male,group C,high school,standard,completed,82,84,82,70,51,6,23
50,male,group E,some college,standard,none,53,55,48,70,73,10,23
51,male,group E,associate's degree,free/reduced,completed,77,69,68,70,10,1,60
52,male,group C,some college,standard,none,53,44,42,70,59,98,60
53,male,group D,high school,standard,none,88,78,75,70,46,21,47
54,female,group C,some high school,free/reduced,completed,71,84,87,70,91,76,14
55,female,group C,high school,free/reduced,none,33,41,43,70,66,22,28
56,female,group E,associate's degree,standard,completed,82,85,86,70,63,20,24
57,male,group D,associate's degree,standard,none,52,55,49,70,85,73,8
58,male,group D,some college,standard,completed,58,59,58,70,33,77,98
59,female,group C,some high school,free/reduced,none,0,17,10,70,49,28,73
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72,70,28,20,34
61,male,group A,some high school,free/reduced,none,39,39,34,70,36,29,24
62,male,group A,associate's degree,free/reduced,none,62,61,55,70,32,15,31
63,female,group C,associate's degree,standard,none,69,80,71,70,21,99,80
64,female,group D,some high school,standard,none,59,58,59,70,92,25,94
65,male,group B,some high school,standard,none,67,64,61,70,3,7,32
66,male,group D,some high school,free/reduced,none,45,37,37,70,69,1,67
67,female,group C,some college,standard,none,60,72,74,70,32,90,21
68,male,group B,associate's degree,free/reduced,none,61,58,56,70,70,11,9
69,female,group C,associate's degree,standard,none,39,64,57,70,95,96,82
70,female,group D,some college,free/reduced,completed,58,63,73,70,15,88,47
71,male,group D,some college,standard,completed,63,55,63,70,8,73,29
72,female,group A,associate's degree,free/reduced,none,41,51,48,70,7,37,53
73,male,group C,some high school,free/reduced,none,61,57,56,70,25,71,7
74,male,group C,some high school,standard,none,49,49,41,70,16,82,68
75,male,group B,associate's degree,free/reduced,none,44,41,38,70,23,49,56
76,male,group E,some high school,standard,none,30,26,22,70,52,66,47
77,male,group A,bachelor's degree,standard,completed,80,78,81,70,34,47,87
78,female,group D,some high school,standard,completed,61,74,72,70,36,83,48
79,female,group E,master's degree,standard,none,62,68,68,70,95,77,87
80,female,group B,associate's degree,standard,none,47,49,50,70,46,4,76
81,male,group B,high school,free/reduced,none,49,45,45,70,15,19,98
82,male,group A,some college,free/reduced,completed,50,47,54,70,18,54,53
83,male,group E,associate's degree,standard,none,72,64,63,70,66,19,63
84,male,group D,high school,free/reduced,none,42,39,34,70,71,65,44
85,female,group C,some college,standard,none,73,80,82,70,48,8,16
86,female,group C,some college,free/reduced,none,76,83,88,70,7,76,38
87,female,group D,associate's degree,standard,none,71,71,74,70,0,7,85
88,female,group A,some college,standard,none,58,70,67,70,46,44,60
89,female,group D,some high school,standard,none,73,86,82,70,7,5,66
90,female,group C,bachelor's degree,standard,none,65,72,74,70,64,6,51
91,male,group C,high school,free/reduced,none,27,34,36,70,79,84,76
92,male,group C,high school,standard,none,71,79,71,70,44,62,68
93,male,group C,associate's degree,free/reduced,completed,43,45,50,70,48,31,22
94,female,group B,some college,standard,none,79,86,92,70,0,83,88
95,male,group C,associate's degree,free/reduced,completed,78,81,82,70,74,32,95
96,male,group B,some high school,standard,completed,65,66,62,70,65,8,45
97,female,group E,some college,standard,completed,63,72,70,70,11,85,76
98,female,group D,some college,free/reduced,none,58,67,62,70,97,56,42
99,female,group D,bachelor's degree,standard,none,65,67,62,70,77,24,82
100,male,group B,some college,standard,none,79,67,67,70,9,18,75
101,male,group D,bachelor's degree,standard,completed,68,74,74,70,86,49,67
102,female,group D,associate's degree,standard,none,85,91,89,70,5,60,96
103,male,group B,high school,standard,completed,60,44,47,70,73,59,34
104,male,group C,some college,standard,completed,98,86,90,70,11,81,72
105,female,group C,some college,standard,none,58,67,72,70,44,87,20
106,female,group D,master's degree,standard,none,87,100,100,70,25,8,27
107,male,group E,associate's degree,standard,completed,66,63,64,70,84,48,54
108,female,group B,associate's degree,free/reduced,none,52,76,70,70,47,81,34
109,female,group B,some high school,standard,none,70,64,72,70,44,95,17
110,female,group D,associate's degree,free/reduced,completed,77,89,98,70,89,50,74
111,male,group C,high school,standard,none,62,55,49,70,39,63,44
112,male,group A,associate's degree,standard,none,54,53,47,70,9,20,29
113,female,group D,some college,standard,none,51,58,54,70,65,9,67
114,female,group E,bachelor's degree,standard,completed,99,100,100,70,29,61,77
115,male,group C,high school,standard,none,84,77,74,70,25,95,68
116,female,group B,bachelor's degree,free/reduced,none,75,85,82,70,20,69,30
117,female,group D,bachelor's degree,standard,none,78,82,79,70,41,72,39
118,female,group D,some high school,standard,none,51,63,61,70,75,44,75
119,female,group C,some college,standard,none,55,69,65,70,36,38,86
120,female,group C,bachelor's degree,standard,completed,79,92,89,70,51,35,66
121,male,group B,associate's degree,standard,completed,91,89,92,70,81,70,62
122,female,group C,some college,standard,completed,88,93,93,70,87,61,83
123,male,group D,high school,free/reduced,none,63,57,56,70,43,36,76
124,male,group E,some college,standard,none,83,80,73,70,20,79,9
125,female,group B,high school,standard,none,87,95,86,70,95,40,53
126,male,group B,some high school,standard,none,72,68,67,70,46,98,3
127,male,group D,some college,standard,completed,65,77,74,70,50,76,64
128,male,group D,master's degree,standard,none,82,82,74,70,75,60,53
129,female,group A,bachelor's degree,standard,none,51,49,51,70,80,76,61
130,male,group D,master's degree,standard,none,89,84,82,70,40,72,67
131,male,group C,some high school,free/reduced,completed,53,37,40,70,46,47,96
132,male,group E,some college,free/reduced,completed,87,74,70,70,2,62,23
133,female,group C,some college,standard,completed,75,81,84,70,65,41,46
134,male,group D,bachelor's degree,free/reduced,completed,74,79,75,70,7,84,57
135,male,group C,bachelor's degree,standard,none,58,55,48,70,90,20,91
136,male,group B,some high school,standard,completed,51,54,41,70,68,65,18
137,male,group E,high school,standard,none,70,55,56,70,15,11,2
138,female,group C,associate's degree,standard,none,59,66,67,70,51,20,57
139,male,group D,some college,standard,completed,71,61,69,70,23,50,38
140,female,group D,some high school,standard,none,76,72,71,70,21,14,39
141,female,group C,some college,free/reduced,none,59,62,64,70,96,14,78
142,female,group E,some college,free/reduced,completed,42,55,54,70,96,25,1
143,male,group A,high school,standard,none,57,43,47,70,81,59,20
144,male,group D,some college,standard,none,88,73,78,70,18,10,77
145,female,group C,some college,free/reduced,none,22,39,33,70,23,85,78
146,male,group B,some high school,standard,none,88,84,75,70,86,96,8
147,male,group C,associate's degree,free/reduced,none,73,68,66,70,58,51,75
148,female,group D,bachelor's degree,standard,completed,68,75,81,70,25,15,59
149,male,group E,associate's degree,free/reduced,completed,100,100,93,70,36,28,65
150,male,group A,some high school,standard,completed,62,67,69,70,74,88,71
151,male,group A,bachelor's degree,standard,none,77,67,68,70,77,1,45
152,female,group B,associate's degree,standard,completed,59,70,66,70,29,37,30
153,male,group D,bachelor's degree,standard,none,54,49,47,70,24,22,90
154,male,group D,some high school,standard,none,62,67,61,70,71,29,74
155,female,group C,some college,standard,completed,70,89,88,70,81,91,23
156,female,group E,high school,free/reduced,completed,66,74,78,70,26,71,21
157,male,group B,some college,free/reduced,none,60,60,60,70,19,24,17
158,female,group B,associate's degree,standard,completed,61,86,87,70,54,2,44
159,male,group D,associate's degree,free/reduced,none,66,62,64,70,34,83,18
160,male,group B,associate's degree,free/reduced,completed,82,78,74,70,29,68,74
161,female,group E,some college,free/reduced,completed,75,88,85,70,23,86,43
162,male,group B,master's degree,free/reduced,none,49,53,52,70,45,74,4
163,male,group C,high school,standard,none,52,53,49,70,3,57,88
164,female,group E,master's degree,standard,none,81,92,91,70,75,3,36
165,female,group C,bachelor's degree,standard,completed,96,100,100,70,16,16,56
166,male,group C,high school,free/reduced,completed,53,51,51,70,74,13,79
167,female,group B,master's degree,free/reduced,completed,58,76,78,70,26,12,41
168,female,group B,high school,standard,completed,68,83,78,70,10,87,78
169,female,group C,some college,free/reduced,completed,67,75,70,70,47,15,98
170,male,group A,high school,standard,completed,72,73,74,70,13,87,98
171,male,group E,some high school,standard,none,94,88,78,70,92,4,69
172,female,group D,some college,standard,none,79,86,81,70,71,97,18
173,female,group C,associate's degree,standard,none,63,67,70,70,40,35,57
174,female,group C,bachelor's degree,free/reduced,completed,43,51,54,70,55,58,14
175,female,group C,master's degree,standard,completed,81,91,87,70,81,11,37
176,female,group B,high school,free/reduced,completed,46,54,58,70,72,39,27
177,female,group C,associate's degree,standard,completed,71,77,77,70,54,89,95
178,female,group B,master's degree,free/reduced,completed,52,70,62,70,21,16,28
179,female,group D,some high school,standard,completed,97,100,100,70,82,69,14
180,male,group C,master's degree,free/reduced,completed,62,68,75,70,67,43,92
181,female,group C,some college,free/reduced,none,46,64,66,70,17,33,38
182,female,group E,high school,standard,none,50,50,47,70,82,50,29
183,female,group D,associate's degree,standard,none,65,69,70,70,16,58,70
184,male,group C,some high school,free/reduced,completed,45,52,49,70,95,26,84
185,male,group C,associate's degree,free/reduced,completed,65,67,65,70,86,94,85
186,male,group E,high school,standard,none,80,76,65,70,84,17,61
187,male,group D,some high school,standard,completed,62,66,68,70,41,7,37
188,male,group B,some high school,free/reduced,none,48,52,45,70,1,19,86
189,female,group C,bachelor's degree,standard,none,77,88,87,70,55,31,48
190,female,group E,associate's degree,standard,none,66,65,69,70,49,20,66
191,male,group D,some college,standard,completed,76,83,79,70,27,30,72
192,female,group B,some high school,standard,none,62,64,66,70,63,29,42
193,male,group D,some college,standard,completed,77,62,62,70,35,42,27
194,female,group C,master's degree,standard,completed,69,84,85,70,12,3,85
195,male,group D,associate's degree,standard,none,61,55,52,70,68,39,18
196,male,group C,some high school,free/reduced,completed,59,69,65,70,43,89,12
197,male,group E,high school,free/reduced,none,55,56,51,70,43,24,48
198,female,group B,some college,free/reduced,none,45,53,55,70,26,4,32
199,female,group B,bachelor's degree,free/reduced,none,78,79,76,70,81,77,94
200,female,group C,associate's degree,standard,completed,67,84,86,70,20,19,80
201,female,group D,some college,free/reduced,none,65,81,77,70,49,28,8
202,male,group C,associate's degree,standard,none,69,77,69,70,62,66,16
203,female,group B,associate's degree,standard,none,57,69,68,70,0,48,48
204,male,group C,some college,standard,none,59,41,42,70,36,89,32
205,male,group D,some high school,standard,completed,74,71,78,70,21,31,14
206,male,group E,bachelor's degree,standard,none,82,62,62,70,87,86,90
207,male,group E,high school,standard,completed,81,80,76,70,37,67,62
208,female,group B,some college,free/reduced,none,74,81,76,70,75,71,80
209,female,group B,some college,free/reduced,none,58,61,66,70,30,67,15
210,male,group D,some high school,free/reduced,completed,80,79,79,70,95,97,56
211,male,group C,some college,free/reduced,none,35,28,27,70,28,41,73
212,female,group C,high school,free/reduced,none,42,62,60,70,9,41,76
213,male,group C,associate's degree,free/reduced,completed,60,51,56,70,4,74,34
214,male,group E,high school,standard,completed,87,91,81,70,74,61,9
215,male,group B,some high school,standard,completed,84,83,75,70,95,80,18
216,female,group E,associate's degree,free/reduced,completed,83,86,88,70,33,32,50
217,female,group C,high school,free/reduced,none,34,42,39,70,25,2,26
218,male,group B,high school,free/reduced,none,66,77,70,70,52,67,93
219,male,group B,some high school,standard,completed,61,56,56,70,85,84,29
220,female,group D,high school,standard,completed,56,68,74,70,25,84,12
221,male,group B,associate's degree,standard,none,87,85,73,70,2,99,24
222,female,group C,some high school,free/reduced,none,55,65,62,70,63,31,71
223,male,group D,some high school,standard,none,86,80,75,70,39,35,77
224,female,group B,associate's degree,standard,completed,52,66,73,70,29,59,28
225,female,group E,master's degree,free/reduced,none,45,56,54,70,51,99,89
226,female,group C,some college,standard,none,72,72,71,70,0,90,46
227,male,group D,high school,standard,none,57,50,54,70,54,80,29
228,male,group A,some high school,free/reduced,none,68,72,64,70,2,89,64
229,female,group C,some college,standard,completed,88,95,94,70,11,15,98
230,male,group D,some college,standard,none,76,64,66,70,34,50,95
231,male,group C,associate's degree,standard,none,46,43,42,70,42,24,34
232,female,group B,bachelor's degree,standard,none,67,86,83,70,79,3,3
233,male,group E,some high school,standard,none,92,87,78,70,28,52,23
234,male,group C,bachelor's degree,standard,completed,83,82,84,70,83,90,82
235,male,group D,associate's degree,standard,none,80,75,77,70,3,98,46
236,male,group D,bachelor's degree,free/reduced,none,63,66,67,70,96,74,50
237,female,group D,some high school,standard,completed,64,60,74,70,54,55,81
238,male,group B,some college,standard,none,54,52,51,70,7,8,67
239,male,group C,associate's degree,standard,none,84,80,80,70,74,90,42
240,male,group D,high school,free/reduced,completed,73,68,66,70,7,1,5
241,female,group E,bachelor's degree,standard,none,80,83,83,70,51,8,74
242,female,group D,high school,standard,none,56,52,55,70,97,95,22
243,male,group E,some college,standard,none,59,51,43,70,26,22,66
244,male,group D,some high school,standard,none,75,74,69,70,39,2,49
245,male,group C,associate's degree,standard,none,85,76,71,70,85,25,11
246,male,group E,associate's degree,standard,none,89,76,74,70,44,36,62
247,female,group B,high school,standard,completed,58,70,68,70,7,23,63
248,female,group B,high school,standard,none,65,64,62,70,0,77,41
249,male,group C,high school,standard,none,68,60,53,70,81,72,59
250,male,group A,some high school,standard,completed,47,49,49,70,97,43,67
251,female,group D,some college,free/reduced,none,71,83,83,70,23,8,73
252,female,group B,some high school,standard,completed,60,70,70,70,2,69,46
253,male,group D,master's degree,standard,none,80,80,72,70,63,29,81
254,male,group D,high school,standard,none,54,52,52,70,76,53,80
255,female,group E,some college,standard,none,62,73,70,70,16,7,19
256,female,group C,associate's degree,free/reduced,none,64,73,68,70,10,24,22
257,male,group C,associate's degree,standard,completed,78,77,77,70,62,78,80
258,female,group B,some college,standard,none,70,75,78,70,88,85,80
259,female,group C,master's degree,free/reduced,completed,65,81,81,70,29,67,30
260,female,group C,some high school,free/reduced,completed,64,79,77,70,49,20,2
261,male,group C,some college,standard,completed,79,79,78,70,48,89,47
262,female,group C,some high school,free/reduced,none,44,50,51,70,52,40,13
263,female,group E,high school,standard,none,99,93,90,70,31,78,11
264,male,group D,high school,standard,none,76,73,68,70,24,42,1
265,male,group D,some high school,free/reduced,none,59,42,41,70,96,66,67
266,female,group C,bachelor's degree,standard,none,63,75,81,70,68,14,46
267,female,group D,high school,standard,none,69,72,77,70,43,94,62
268,female,group D,associate's degree,standard,completed,88,92,95,70,62,23,50
269,female,group E,some college,free/reduced,none,71,76,70,70,90,60,34
270,male,group C,bachelor's degree,standard,none,69,63,61,70,92,46,63
271,male,group C,some college,standard,none,58,49,42,70,66,61,43
272,female,group D,associate's degree,free/reduced,none,47,53,58,70,67,77,23
273,female,group D,some college,standard,none,65,70,71,70,6,87,80
274,male,group B,some college,standard,completed,88,85,76,70,89,54,63
275,male,group C,bachelor's degree,standard,none,83,78,73,70,27,55,14
276,female,group C,some high school,standard,completed,85,92,93,70,9,98,26
277,female,group E,high school,standard,completed,59,63,75,70,88,49,16

# insert()
    Insert a new column at a specific position or index

In [170]:
#using index() to add a column at a specific position
df_exam.insert(1,'example',series1)

In [172]:
df_exam

,gender,example,haw,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,langauage,language score
0,female,2,2,2,group B,bachelor's degree,standard,none,72,72,74,70,58
1,female,21,21,21,group C,some college,standard,completed,69,90,88,70,62
2,female,6,6,6,group B,master's degree,standard,none,90,95,93,70,50
3,male,54,54,54,group A,associate's degree,free/reduced,none,47,57,44,70,67
4,male,38,38,38,group C,some college,standard,none,76,78,75,70,95
5,female,65,65,65,group B,associate's degree,standard,none,71,83,78,70,63
6,female,90,90,90,group B,some college,standard,completed,88,95,92,70,70
7,male,70,70,70,group B,some college,free/reduced,none,40,43,39,70,93
8,male,82,82,82,group D,high school,free/reduced,completed,64,64,67,70,53
9,female,40,40,40,group B,high school,free/reduced,none,38,60,50,70,19
10,male,71,71,71,group C,associate's degree,standard,none,58,54,52,70,94
11,male,11,11,11,group D,associate's degree,standard,none,40,52,43,70,87
12,female,82,82,82,group B,high school,standard,none,65,81,73,70,6
13,male,22,22,22,group A,some college,standard,completed,78,72,70,70,15
14,female,35,35,35,group A,master's degree,standard,none,50,53,58,70,64
15,female,75,75,75,group C,some high school,standard,none,69,75,78,70,39
16,male,81,81,81,group C,high school,standard,none,88,89,86,70,78
17,female,30,30,30,group B,some high school,free/reduced,none,18,32,28,70,29
18,male,44,44,44,group C,master's degree,free/reduced,completed,46,42,46,70,31
19,female,76,76,76,group C,associate's degree,free/reduced,none,54,58,61,70,62
20,male,20,20,20,group D,high school,standard,none,66,69,63,70,14
21,female,7,7,7,group B,some college,free/reduced,completed,65,75,70,70,62
22,male,10,10,10,group D,some college,standard,none,44,54,53,70,62
23,female,34,34,34,group C,some high school,standard,none,69,73,73,70,20
24,male,93,93,93,group D,bachelor's degree,free/reduced,completed,74,71,80,70,85
25,male,38,38,38,group A,master's degree,free/reduced,none,73,74,72,70,89
26,male,65,65,65,group B,some college,standard,none,69,54,55,70,96
27,female,54,54,54,group C,bachelor's degree,standard,none,67,69,75,70,14
28,male,91,91,91,group C,high school,standard,none,70,70,65,70,69
29,female,21,21,21,group D,master's degree,standard,none,62,70,75,70,3
30,female,64,64,64,group D,some college,standard,none,69,74,74,70,52
31,female,29,29,29,group B,some college,standard,none,63,65,61,70,24
32,female,57,57,57,group E,master's degree,free/reduced,none,56,72,65,70,62
33,male,25,25,25,group D,some college,standard,none,40,42,38,70,56
34,male,17,17,17,group E,some college,standard,none,97,87,82,70,98
35,male,27,27,27,group E,associate's degree,standard,completed,81,81,79,70,2
36,female,83,83,83,group D,associate's degree,standard,none,74,81,83,70,1
37,female,13,13,13,group D,some high school,free/reduced,none,50,64,59,70,24
38,female,87,87,87,group D,associate's degree,free/reduced,completed,75,90,88,70,36
39,male,90,90,90,group B,associate's degree,free/reduced,none,57,56,57,70,94
40,male,75,75,75,group C,associate's degree,free/reduced,none,55,61,54,70,48
41,female,27,27,27,group C,associate's degree,standard,none,58,73,68,70,43
42,female,50,50,50,group B,associate's degree,standard,none,53,58,65,70,83
43,male,55,55,55,group B,some college,free/reduced,completed,59,65,66,70,78
44,female,86,86,86,group E,associate's degree,free/reduced,none,50,56,54,70,66
45,male,28,28,28,group B,associate's degree,standard,none,65,54,57,70,99
46,female,92,92,92,group A,associate's degree,standard,completed,55,65,62,70,37
47,female,97,97,97,group C,high school,standard,none,66,71,76,70,37
48,female,58,58,58,group D,associate's degree,free/reduced,completed,57,74,76,70,20
49,male,6,6,6,group C,high school,standard,completed,82,84,82,70,51
50,male,10,10,10,group E,some college,standard,none,53,55,48,70,73
51,male,1,1,1,group E,associate's degree,free/reduced,completed,77,69,68,70,10
52,male,98,98,98,group C,some college,standard,none,53,44,42,70,59
53,male,21,21,21,group D,high school,standard,none,88,78,75,70,46
54,female,76,76,76,group C,some high school,free/reduced,completed,71,84,87,70,91
55,female,22,22,22,group C,high school,free/reduced,none,33,41,43,70,66
56,female,20,20,20,group E,associate's degree,standard,completed,82,85,86,70,63
57,male,73,73,73,group D,associate's degree,standard,none,52,55,49,70,85
58,male,77,77,77,group D,some college,standard,completed,58,59,58,70,33
59,female,28,28,28,group C,some high school,free/reduced,none,0,17,10,70,49
60,male,20,20,20,group E,bachelor's degree,free/reduced,completed,79,74,72,70,28
61,male,29,29,29,group A,some high school,free/reduced,none,39,39,34,70,36
62,male,15,15,15,group A,associate's degree,free/reduced,none,62,61,55,70,32
63,female,99,99,99,group C,associate's degree,standard,none,69,80,71,70,21
64,female,25,25,25,group D,some high school,standard,none,59,58,59,70,92
65,male,7,7,7,group B,some high school,standard,none,67,64,61,70,3
66,male,1,1,1,group D,some high school,free/reduced,none,45,37,37,70,69
67,female,90,90,90,group C,some college,standard,none,60,72,74,70,32
68,male,11,11,11,group B,associate's degree,free/reduced,none,61,58,56,70,70
69,female,96,96,96,group C,associate's degree,standard,none,39,64,57,70,95
70,female,88,88,88,group D,some college,free/reduced,completed,58,63,73,70,15
71,male,73,73,73,group D,some college,standard,completed,63,55,63,70,8
72,female,37,37,37,group A,associate's degree,free/reduced,none,41,51,48,70,7
73,male,71,71,71,group C,some high school,free/reduced,none,61,57,56,70,25
74,male,82,82,82,group C,some high school,standard,none,49,49,41,70,16
75,male,49,49,49,group B,associate's degree,free/reduced,none,44,41,38,70,23
76,male,66,66,66,group E,some high school,standard,none,30,26,22,70,52
77,male,47,47,47,group A,bachelor's degree,standard,completed,80,78,81,70,34
78,female,83,83,83,group D,some high school,standard,completed,61,74,72,70,36
79,female,77,77,77,group E,master's degree,standard,none,62,68,68,70,95
80,female,4,4,4,group B,associate's degree,standard,none,47,49,50,70,46
81,male,19,19,19,group B,high school,free/reduced,none,49,45,45,70,15
82,male,54,54,54,group A,some college,free/reduced,completed,50,47,54,70,18
83,male,19,19,19,group E,associate's degree,standard,none,72,64,63,70,66
84,male,65,65,65,group D,high school,free/reduced,none,42,39,34,70,71
85,female,8,8,8,group C,some college,standard,none,73,80,82,70,48
86,female,76,76,76,group C,some college,free/reduced,none,76,83,88,70,7
87,female,7,7,7,group D,associate's degree,standard,none,71,71,74,70,0
88,female,44,44,44,group A,some college,standard,none,58,70,67,70,46
89,female,5,5,5,group D,some high school,standard,none,73,86,82,70,7
90,female,6,6,6,group C,bachelor's degree,standard,none,65,72,74,70,64
91,male,84,84,84,group C,high school,free/reduced,none,27,34,36,70,79
92,male,62,62,62,group C,high school,standard,none,71,79,71,70,44
93,male,31,31,31,group C,associate's degree,free/reduced,completed,43,45,50,70,48
94,female,83,83,83,group B,some college,standard,none,79,86,92,70,0
95,male,32,32,32,group C,associate's degree,free/reduced,completed,78,81,82,70,74
96,male,8,8,8,group B,some high school,standard,completed,65,66,62,70,65
97,female,85,85,85,group E,some college,standard,completed,63,72,70,70,11
98,female,56,56,56,group D,some college,free/reduced,none,58,67,62,70,97
99,female,24,24,24,group D,bachelor's degree,standard,none,65,67,62,70,77
100,male,18,18,18,group B,some college,standard,none,79,67,67,70,9
101,male,49,49,49,group D,bachelor's degree,standard,completed,68,74,74,70,86
102,female,60,60,60,group D,associate's degree,standard,none,85,91,89,70,5
103,male,59,59,59,group B,high school,standard,completed,60,44,47,70,73
104,male,81,81,81,group C,some college,standard,completed,98,86,90,70,11
105,female,87,87,87,group C,some college,standard,none,58,67,72,70,44
106,female,8,8,8,group D,master's degree,standard,none,87,100,100,70,25
107,male,48,48,48,group E,associate's degree,standard,completed,66,63,64,70,84
108,female,81,81,81,group B,associate's degree,free/reduced,none,52,76,70,70,47
109,female,95,95,95,group B,some high school,standard,none,70,64,72,70,44
110,female,50,50,50,group D,associate's degree,free/reduced,completed,77,89,98,70,89
111,male,63,63,63,group C,high school,standard,none,62,55,49,70,39
112,male,20,20,20,group A,associate's degree,standard,none,54,53,47,70,9
113,female,9,9,9,group D,some college,standard,none,51,58,54,70,65
114,female,61,61,61,group E,bachelor's degree,standard,completed,99,100,100,70,29
115,male,95,95,95,group C,high school,standard,none,84,77,74,70,25
116,female,69,69,69,group B,bachelor's degree,free/reduced,none,75,85,82,70,20
117,female,72,72,72,group D,bachelor's degree,standard,none,78,82,79,70,41
118,female,44,44,44,group D,some high school,standard,none,51,63,61,70,75
119,female,38,38,38,group C,some college,standard,none,55,69,65,70,36
120,female,35,35,35,group C,bachelor's degree,standard,completed,79,92,89,70,51
121,male,70,70,70,group B,associate's degree,standard,completed,91,89,92,70,81
122,female,61,61,61,group C,some college,standard,completed,88,93,93,70,87
123,male,36,36,36,group D,high school,free/reduced,none,63,57,56,70,43
124,male,79,79,79,group E,some college,standard,none,83,80,73,70,20
125,female,40,40,40,group B,high school,standard,none,87,95,86,70,95
126,male,98,98,98,group B,some high school,standard,none,72,68,67,70,46
127,male,76,76,76,group D,some college,standard,completed,65,77,74,70,50
128,male,60,60,60,group D,master's degree,standard,none,82,82,74,70,75
129,female,76,76,76,group A,bachelor's degree,standard,none,51,49,51,70,80
130,male,72,72,72,group D,master's degree,standard,none,89,84,82,70,40
131,male,47,47,47,group C,some high school,free/reduced,completed,53,37,40,70,46
132,male,62,62,62,group E,some college,free/reduced,completed,87,74,70,70,2
133,female,41,41,41,group C,some college,standard,completed,75,81,84,70,65
134,male,84,84,84,group D,bachelor's degree,free/reduced,completed,74,79,75,70,7
135,male,20,20,20,group C,bachelor's degree,standard,none,58,55,48,70,90
136,male,65,65,65,group B,some high school,standard,completed,51,54,41,70,68
137,male,11,11,11,group E,high school,standard,none,70,55,56,70,15
138,female,20,20,20,group C,associate's degree,standard,none,59,66,67,70,51
139,male,50,50,50,group D,some college,standard,completed,71,61,69,70,23
140,female,14,14,14,group D,some high school,standard,none,76,72,71,70,21
141,female,14,14,14,group C,some college,free/reduced,none,59,62,64,70,96
142,female,25,25,25,group E,some college,free/reduced,completed,42,55,54,70,96
143,male,59,59,59,group A,high school,standard,none,57,43,47,70,81
144,male,10,10,10,group D,some college,standard,none,88,73,78,70,18
145,female,85,85,85,group C,some college,free/reduced,none,22,39,33,70,23
146,male,96,96,96,group B,some high school,standard,none,88,84,75,70,86
147,male,51,51,51,group C,associate's degree,free/reduced,none,73,68,66,70,58
148,female,15,15,15,group D,bachelor's degree,standard,completed,68,75,81,70,25
149,male,28,28,28,group E,associate's degree,free/reduced,completed,100,100,93,70,36
150,male,88,88,88,group A,some high school,standard,completed,62,67,69,70,74
151,male,1,1,1,group A,bachelor's degree,standard,none,77,67,68,70,77
152,female,37,37,37,group B,associate's degree,standard,completed,59,70,66,70,29
153,male,22,22,22,group D,bachelor's degree,standard,none,54,49,47,70,24
154,male,29,29,29,group D,some high school,standard,none,62,67,61,70,71
155,female,91,91,91,group C,some college,standard,completed,70,89,88,70,81
156,female,71,71,71,group E,high school,free/reduced,completed,66,74,78,70,26
157,male,24,24,24,group B,some college,free/reduced,none,60,60,60,70,19
158,female,2,2,2,group B,associate's degree,standard,completed,61,86,87,70,54
159,male,83,83,83,group D,associate's degree,free/reduced,none,66,62,64,70,34
160,male,68,68,68,group B,associate's degree,free/reduced,completed,82,78,74,70,29
161,female,86,86,86,group E,some college,free/reduced,completed,75,88,85,70,23
162,male,74,74,74,group B,master's degree,free/reduced,none,49,53,52,70,45
163,male,57,57,57,group C,high school,standard,none,52,53,49,70,3
164,female,3,3,3,group E,master's degree,standard,none,81,92,91,70,75
165,female,16,16,16,group C,bachelor's degree,standard,completed,96,100,100,70,16
166,male,13,13,13,group C,high school,free/reduced,completed,53,51,51,70,74
167,female,12,12,12,group B,master's degree,free/reduced,completed,58,76,78,70,26
168,female,87,87,87,group B,high school,standard,completed,68,83,78,70,10
169,female,15,15,15,group C,some college,free/reduced,completed,67,75,70,70,47
170,male,87,87,87,group A,high school,standard,completed,72,73,74,70,13
171,male,4,4,4,group E,some high school,standard,none,94,88,78,70,92
172,female,97,97,97,group D,some college,standard,none,79,86,81,70,71
173,female,35,35,35,group C,associate's degree,standard,none,63,67,70,70,40
174,female,58,58,58,group C,bachelor's degree,free/reduced,completed,43,51,54,70,55
175,female,11,11,11,group C,master's degree,standard,completed,81,91,87,70,81
176,female,39,39,39,group B,high school,free/reduced,completed,46,54,58,70,72
177,female,89,89,89,group C,associate's degree,standard,completed,71,77,77,70,54
178,female,16,16,16,group B,master's degree,free/reduced,completed,52,70,62,70,21
179,female,69,69,69,group D,some high school,standard,completed,97,100,100,70,82
180,male,43,43,43,group C,master's degree,free/reduced,completed,62,68,75,70,67
181,female,33,33,33,group C,some college,free/reduced,none,46,64,66,70,17
182,female,50,50,50,group E,high school,standard,none,50,50,47,70,82
183,female,58,58,58,group D,associate's degree,standard,none,65,69,70,70,16
184,male,26,26,26,group C,some high school,free/reduced,completed,45,52,49,70,95
185,male,94,94,94,group C,associate's degree,free/reduced,completed,65,67,65,70,86
186,male,17,17,17,group E,high school,standard,none,80,76,65,70,84
187,male,7,7,7,group D,some high school,standard,completed,62,66,68,70,41
188,male,19,19,19,group B,some high school,free/reduced,none,48,52,45,70,1
189,female,31,31,31,group C,bachelor's degree,standard,none,77,88,87,70,55
190,female,20,20,20,group E,associate's degree,standard,none,66,65,69,70,49
191,male,30,30,30,group D,some college,standard,completed,76,83,79,70,27
192,female,29,29,29,group B,some high school,standard,none,62,64,66,70,63
193,male,42,42,42,group D,some college,standard,completed,77,62,62,70,35
194,female,3,3,3,group C,master's degree,standard,completed,69,84,85,70,12
195,male,39,39,39,group D,associate's degree,standard,none,61,55,52,70,68
196,male,89,89,89,group C,some high school,free/reduced,completed,59,69,65,70,43
197,male,24,24,24,group E,high school,free/reduced,none,55,56,51,70,43
198,female,4,4,4,group B,some college,free/reduced,none,45,53,55,70,26
199,female,77,77,77,group B,bachelor's degree,free/reduced,none,78,79,76,70,81
200,female,19,19,19,group C,associate's degree,standard,completed,67,84,86,70,20
201,female,28,28,28,group D,some college,free/reduced,none,65,81,77,70,49
202,male,66,66,66,group C,associate's degree,standard,none,69,77,69,70,62
203,female,48,48,48,group B,associate's degree,standard,none,57,69,68,70,0
204,male,89,89,89,group C,some college,standard,none,59,41,42,70,36
205,male,31,31,31,group D,some high school,standard,completed,74,71,78,70,21
206,male,86,86,86,group E,bachelor's degree,standard,none,82,62,62,70,87
207,male,67,67,67,group E,high school,standard,completed,81,80,76,70,37
208,female,71,71,71,group B,some college,free/reduced,none,74,81,76,70,75
209,female,67,67,67,group B,some college,free/reduced,none,58,61,66,70,30
210,male,97,97,97,group D,some high school,free/reduced,completed,80,79,79,70,95
211,male,41,41,41,group C,some college,free/reduced,none,35,28,27,70,28
212,female,41,41,41,group C,high school,free/reduced,none,42,62,60,70,9
213,male,74,74,74,group C,associate's degree,free/reduced,completed,60,51,56,70,4
214,male,61,61,61,group E,high school,standard,completed,87,91,81,70,74
215,male,80,80,80,group B,some high school,standard,completed,84,83,75,70,95
216,female,32,32,32,group E,associate's degree,free/reduced,completed,83,86,88,70,33
217,female,2,2,2,group C,high school,free/reduced,none,34,42,39,70,25
218,male,67,67,67,group B,high school,free/reduced,none,66,77,70,70,52
219,male,84,84,84,group B,some high school,standard,completed,61,56,56,70,85
220,female,84,84,84,group D,high school,standard,completed,56,68,74,70,25
221,male,99,99,99,group B,associate's degree,standard,none,87,85,73,70,2
222,female,31,31,31,group C,some high school,free/reduced,none,55,65,62,70,63
223,male,35,35,35,group D,some high school,standard,none,86,80,75,70,39
224,female,59,59,59,group B,associate's degree,standard,completed,52,66,73,70,29
225,female,99,99,99,group E,master's degree,free/reduced,none,45,56,54,70,51
226,female,90,90,90,group C,some college,standard,none,72,72,71,70,0
227,male,80,80,80,group D,high school,standard,none,57,50,54,70,54
228,male,89,89,89,group A,some high school,free/reduced,none,68,72,64,70,2
229,female,15,15,15,group C,some college,standard,completed,88,95,94,70,11
230,male,50,50,50,group D,some college,standard,none,76,64,66,70,34
231,male,24,24,24,group C,associate's degree,standard,none,46,43,42,70,42
232,female,3,3,3,group B,bachelor's degree,standard,none,67,86,83,70,79
233,male,52,52,52,group E,some high school,standard,none,92,87,78,70,28
234,male,90,90,90,group C,bachelor's degree,standard,completed,83,82,84,70,83
235,male,98,98,98,group D,associate's degree,standard,none,80,75,77,70,3
236,male,74,74,74,group D,bachelor's degree,free/reduced,none,63,66,67,70,96
237,female,55,55,55,group D,some high school,standard,completed,64,60,74,70,54
238,male,8,8,8,group B,some college,standard,none,54,52,51,70,7
239,male,90,90,90,group C,associate's degree,standard,none,84,80,80,70,74
240,male,1,1,1,group D,high school,free/reduced,completed,73,68,66,70,7
241,female,8,8,8,group E,bachelor's degree,standard,none,80,83,83,70,51
242,female,95,95,95,group D,high school,standard,none,56,52,55,70,97
243,male,22,22,22,group E,some college,standard,none,59,51,43,70,26
244,male,2,2,2,group D,some high school,standard,none,75,74,69,70,39
245,male,25,25,25,group C,associate's degree,standard,none,85,76,71,70,85
246,male,36,36,36,group E,associate's degree,standard,none,89,76,74,70,44
247,female,23,23,23,group B,high school,standard,completed,58,70,68,70,7
248,female,77,77,77,group B,high school,standard,none,65,64,62,70,0
249,male,72,72,72,group C,high school,standard,none,68,60,53,70,81
250,male,43,43,43,group A,some high school,standard,completed,47,49,49,70,97
251,female,8,8,8,group D,some college,free/reduced,none,71,83,83,70,23
252,female,69,69,69,group B,some high school,standard,completed,60,70,70,70,2
253,male,29,29,29,group D,master's degree,standard,none,80,80,72,70,63
254,male,53,53,53,group D,high school,standard,none,54,52,52,70,76
255,female,7,7,7,group E,some college,standard,none,62,73,70,70,16
256,female,24,24,24,group C,associate's degree,free/reduced,none,64,73,68,70,10
257,male,78,78,78,group C,associate's degree,standard,completed,78,77,77,70,62
258,female,85,85,85,group B,some college,standard,none,70,75,78,70,88
259,female,67,67,67,group C,master's degree,free/reduced,completed,65,81,81,70,29
260,female,20,20,20,group C,some high school,free/reduced,completed,64,79,77,70,49
261,male,89,89,89,group C,some college,standard,completed,79,79,78,70,48
262,female,40,40,40,group C,some high school,free/reduced,none,44,50,51,70,52
263,female,78,78,78,group E,high school,standard,none,99,93,90,70,31
264,male,42,42,42,group D,high school,standard,none,76,73,68,70,24
265,male,66,66,66,group D,some high school,free/reduced,none,59,42,41,70,96
266,female,14,14,14,group C,bachelor's degree,standard,none,63,75,81,70,68
267,female,94,94,94,group D,high school,standard,none,69,72,77,70,43