# concat()

# Concatenate vertically

In [114]:
import pandas as pd

In [115]:
df1=pd.DataFrame({'id':['A','B','C','D'],
                   'age':[30,23,25,22]})
df2=pd.DataFrame({'id':['E','F','G','F'],
                   'age':[40,21,19,24]})

In [116]:
# vertical concatinate(axis=0)
pd.concat([df1,df2],axis=0,ignore_index=True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  F   24

# Concatenate horizontally

In [118]:
df1=pd.DataFrame({'id':['A','B','C','D'],
                   'age':[30,23,25,22]})
df2=pd.DataFrame({'job':['Doctor','Statistician',
                        'Accountant','Developer']})

In [119]:
pd.concat([df1,df2],axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer