In [1]:
import pandas as pd

In [5]:
df=pd.read_csv('Players_20.csv')
#set index
df.set_index('short_name',inplace=True)
# select columns
df=df[['long_name',	'age', 'dob',	'height_cm',	'weight_kg',	'nationality', 'club']]

# Drop row

In [12]:
#drop one row
#axis parameter
df.drop('L. Messi',axis=0)
#index parameter
df.drop(index=['L. Messi'])

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [14]:
#drop two or more rows and update data(inplace=True)
df.drop(['L. Messi','Cristiano Ronaldo'],axis=0,inplace=True)
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Drop Column

In [19]:
# Drop column
# axis parameter
df.drop('long_name',axis=1)
# column parameter
df.drop(columns=['long_name'])

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [27]:
# drop column by position/index (drop last column)
df.columns[[-1]]
df.drop(df.columns[[-1]],axis=1)

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany
...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR
Zhang Wei,张威,19,2000-05-16,186,75,China PR
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR

In [37]:
#drop two or more columns and update data (inplace=True)
df.drop(['long_name','dob'],axis=1,inplace=True)

KeyError: "['long_name', 'dob'] not found in axis"