In [1]:
import pandas as pd

In [13]:
df=pd.read_csv('players_20.csv')
df.set_index('short_name',inplace=True)
df=df[['long_name',	'age', 'dob',	'height_cm',	'weight_kg',	'nationality', 'club']]

In [15]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# selecting with a single value
 loc[row_label,column_label]

In [18]:
# get all data about C.Ronaldo
df.loc['Cristiano Ronaldo']

long_name      Cristiano Ronaldo dos Santos Aveiro
age                                             34
dob                                     1985-02-05
height_cm                                      187
weight_kg                                       83
nationality                               Portugal
club                                      Juventus
Name: Cristiano Ronaldo, dtype: object

In [20]:
df.loc['Cristiano Ronaldo','height_cm']

187

In [26]:
# get all rows inside the 'height_cm' column
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [28]:
#get all columns that correspond to the index 'C.Ronaldo'
df.loc['Cristiano Ronaldo',:]

long_name      Cristiano Ronaldo dos Santos Aveiro
age                                             34
dob                                     1985-02-05
height_cm                                      187
weight_kg                                       83
nationality                               Portugal
club                                      Juventus
Name: Cristiano Ronaldo, dtype: object

# 2 Selecting with the list of values

In [33]:
#get all data about c.ronaldo and l.messi
df.loc[['Cristiano Ronaldo','L. Messi']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona

In [35]:
#get height of both players
df.loc[['L. Messi','Cristiano Ronaldo'],'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [41]:
#get the  height and weight of c ronaldo
df.loc['Cristiano Ronaldo',['height_cm','weight_kg']]

height_cm    187
weight_kg     83
Name: Cristiano Ronaldo, dtype: object

In [43]:
#get height and weight of both players
df.loc[['L. Messi','Cristiano Ronaldo'],['height_cm','weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

In [ ]:
s