In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('players_20.csv')
df.set_index('short_name',inplace=True)
df=df[['long_name',	'age', 'dob',	'height_cm',	'weight_kg',	'nationality', 'club']]

In [5]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Selecting with a single value
  iloc[row_position,column_position]

In [16]:
# get the height of Cristiano Ronaldo
df.iloc[1,3]

187

In [18]:
# get the weight of Cristiano Ronaldo
df.iloc[1,4]

83

In [20]:
#get all rows inside the 'height_cm column'
df.iloc[:,3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [22]:
#get all column that correspond to the index 'Cristiano Ronaldo'
df.iloc[1,:]

long_name      Cristiano Ronaldo dos Santos Aveiro
age                                             34
dob                                     1985-02-05
height_cm                                      187
weight_kg                                       83
nationality                               Portugal
club                                      Juventus
Name: Cristiano Ronaldo, dtype: object

# Selecting with a list of values

In [33]:
#get all the data about Cristiano Ronaldo and L. Messi
df.iloc[[0,1]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [37]:
# get the height of Cristiano Ronaldo and L. Messi
df.iloc[[0,1],3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [39]:
# get height and weight of c ronaldo
df.iloc[1,[3,4]]

height_cm    187
weight_kg     83
Name: Cristiano Ronaldo, dtype: object

In [41]:
# get height and weight of c ronaldo and l messi
df.iloc[[0,1],[3,4]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

# Selecting a range of data with a slice
  start:stop(note that the start is included but the stop is excluded)

In [58]:
#slice column lables age/club
players=[0,1]
df.iloc[players,1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [68]:
#slice index lables(top1 to top10 players
df.iloc[0:10,1:5]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

# Selecting with conditions
  iloc cannot accept the boolean series, but only a boolean list. we have to use the list() function to convert a series into a boolean list

In [79]:
#one condition:select player with height above 180cm
df.iloc[list(df['height_cm']>180),1:5]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [103]:
#multiple conditions : select a player with height above 180cm from portugal
df.iloc[list((df['height_cm'] > 180) & (df['nationality']=="Portugal")),:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
A. Lopes,Anthony Lopes,28,1990-10-01,184,81,Portugal,Olympique Lyonnais
João Cancelo,João Pedro Cavaco Cancelo,25,1994-05-27,182,74,Portugal,Manchester City
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
William Carvalho,William Silva de Carvalho,27,1992-04-07,187,83,Portugal,Real Betis
...,...,...,...,...,...,...,...
João Pereira,João Duarte Vieira Pereira,29,1990-05-10,183,79,Portugal,SønderjyskE
Rúben Fonseca,Rúben Miguel Valente Fonseca,19,2000-02-24,188,82,Portugal,CD Tondela
Filipe Ferreira,Filipe Ferreira Marques,21,1998-02-25,186,73,Portugal,CF Fuenlabrada
Wilson Carvalho,Wilson Roberto Bento De Carvalho,25,1993-07-04,183,77,Portugal,Accrington Stanley
Alexandre Pimenta,A. Pimenta Flora Pimenta,20,1999-03-02,184,75,Portugal,Venezia FC